### ISSUE TITLE
安装后YCM的问题，YouCompleteMe unavailable: unable to load Python. 请按 ENTER 或其它命令继续

### ISSUE THREAD

**Issue by xindelvcheng** [chxuan/vimplus#106]
每次打开vim都会提示错误不能用YCM，vim是源码安装的，试了到YCM执行./install.py --clang-completer，系统试过一个Ubuntu18.04一个Deepin15.9，其他插件好像能用。

**Comment by colorsakura** [comment]
应该是vim不支持Python2，直接python3 install.py 试试

**Comment by xindelvcheng** [comment]
当时安装用的就是在~/.vim/plugged/YouCompleteMe运行`python3 install.py `
```
Searching Python 3.6 libraries...
Found Python library: /usr/lib/python3.6/config-3.6m-x86_64-linux-gnu/libpython3.6.so
Found Python headers folder: /usr/include/python3.6m
.......
Scanning dependencies of target _regex
[ 66%] Building C object CMakeFiles/_regex.dir/regex_3/_regex_unicode.c.o
[ 66%] Building C object CMakeFiles/_regex.dir/regex_3/_regex.c.o
[100%] Linking C shared library /home/zhangweizhen/.vim/plugged/YouCompleteMe/third_party/ycmd/third_party/cregex/regex_3/_regex.so
[100%] Built target _regex
```
然后运行`vim`还是
```
YouCompleteMe unavailable: unable to load Python.
请按 ENTER 或其它命令继续
```
我Google没查到这个错误

**Comment by colorsakura** [comment]
vim --version 看看支不支持python3

**Comment by xindelvcheng** [comment]
源码安装的，应该支持
```
......
+comments          +libcall           +python/dyn        +visualextra
+conceal           +linebreak         +python3/dyn       +viminfo
......
```

**Comment by colorsakura** [comment]
https://github.com/davidhalter/jedi-vim/issues/66

**Comment by xindelvcheng** [comment]
似乎是我没看到`Note for Ubuntu users: You can only use Python 2 or Python 3. If you try to compile vim with both python-config-dir and python3-config-dir, YouCompleteMe will give you an error YouCompleteMe unavailable: requires Vim compiled with Python (2.6+ or 3.3+) support, when you start VIM.`这句话。不过又编译一次还是`let: g:ycm_path_to_python_interpreter=$python_interpreter: 表达式中有语法错误`最后没办法找了两句指令搞定了
```
sudo apt-get install vim-youcompleteme
vim-addons install youcompleteme
```

**Comment by xindelvcheng** [comment]
YCM居然可以直接apt

**Comment by xiaozhi16** [comment]
我出现该问题的原因是源码编译前的configure有误，通过如下方法得到解决
[https://stackoverflow.com/questions/61240101/youcompleteme-unavailable-unable-to-load-python](url)
