### ISSUE TITLE
没人解决

### ISSUE THREAD

**Issue by chenchuangchn** [chxuan/vimplus#11]
很垃圾，遇到问题没有支持，#if #endif 有问题。还是用别人的吧

**Comment by chxuan** [comment]
遇到什么问题，请具体描述下

**Comment by i0Ek3** [comment]
不是所有问题都会被及时看到，请耐心等待，也请尊重别人的成果！如果只愿做伸手党，就别那么多要求！@chenchuangchn

**Comment by rookiebird** [comment]
对啊，对于作为一个用了两个月linux的小白，这个项目对我来说真的很棒的，请不要随便吐槽博主，也希望博主加油，多多加油，有很多像我这样的小白得靠博主带飞的

**Comment by chenchuangchn** [comment]
首先，我对博主的出言不逊向您表示道歉，以及对代码贡献出来感到钦佩。但是，那些为博主打抱不平的，我很鄙视你@i0Ek3 @rookiebird ，你们真的用过吗，难道用的时候一点问题都没有？
其次我说下问题：
1. “can't jump to defination”我之前提过这个issue。
2. 用这个东西，我代码中的#if 0 #endif对中，如果#endif不在行首，检测不到，导致的想想就是，#if 0之后全是黑色的。
3. 这个是建议，我认为vim中那些基本的快捷键是不建议修改的，ctrl+f做成了搜索，那如何向前翻页，快捷键的说明文档在哪里。
最后，我觉得对一个项目的尊重在于完善它，而不是对它夸夸其谈。很失望我看到都是对没有意义的评论。

**Comment by i0Ek3** [comment]
@chenchuangchn 
对于您的鄙视我表示很伤心，我决定下课后必须面壁思过！至少我要思考下我的评论到底是哪里做的不周到让您还有鄙视之心？
其次，可能您的眼光更高吧？至少在我这种用户用来，还没有遇到您这样的问题（很遗憾没能遇到像您描述的问题）！
不过值得肯定的是，您意识到自己的问题并向博主道歉，这点是好的（请给自己鼓掌）。
至于其他的问题：既然有能力，何不自己动手？
最后，很高兴您能说出像“对一个项目的尊重在于完善它”这样的声音，然而您却妄想通过言论来改善该问题，我很失望您没有直接写出一个niubility的vim供大家使用！
