### ISSUE TITLE
ｖｉｍ-devicons显示乱码

### ISSUE THREAD

**Issue by i0Ek3** [chxuan/vimplus#12]
我是KUBUNTU17.04的系统，内置的组件版本也都是最新的。执行./install没什么大问题，就是ycm是中途重新编译的，最后一切正常，唯独ｖｉｍ-devicons显示乱码，是需要更换系统字体吗？试了下更改终端字体格式------>没有成功，，改了下系统的也没成，不知该如何解决。昨天在16.04上还正常！

**Comment by OvenGuo0224** [comment]
Droid Sans Mono for Powerline Nerd Font Complete

**Comment by OvenGuo0224** [comment]
需要把终端改成这个字体

**Comment by i0Ek3** [comment]
@OvenGuo0224，Merci～I did it with you method!^_^
