### ISSUE TITLE
Mac安装成功后运行失败，提示Caught deadly signal SEGV

### ISSUE THREAD

**Issue by lianrzh** [chxuan/vimplus#120]
如题。
环境mac10.14
更详细的信息：
Vim: Caught deadly signal SEGV
Error detected while processing function <SNR>113_PollServerReady[7]..<SNR>113_Pyeval:Vim: Finished.

line    4:
Exception MemoryError: MemoryError() in <module 'threading' from '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.pyc'> ignored
[1]    17737 segmentation fault  vim

**Comment by wangcaimeng** [comment]
我也遇到了同样的问题 请问怎么解决的

**Comment by zkywalker** [comment]
> 我也遇到了同样的问题 请问怎么解决的

rm ~/.vimrc
