### ISSUE TITLE
.c 头文件文件引用显示未错误

### ISSUE THREAD

**Issue by laiqb** [chxuan/vimplus#124]
现在有一个.h和.cc文件，打开.cc文件后，会有红色的下划线，提示找不到对应的文件，这个文件的确是在这个文件夹下面。如图所示的 第一行#inlcude "lib/hello-time.h"标红线了。如果将这个引用修改为#include "hello-time.h"此时是正常的。我觉得这个应该是有地方可以修改下配置的吧。
![1](https://user-images.githubusercontent.com/11612829/54968955-714d1f80-4fb7-11e9-8d25-13464f206604.png)

**Comment by chxuan** [comment]
@laiqb 首先要确认下ycm是否按照完成并可以正常使用。

**Comment by laiqb** [comment]
@chxuan 可以正常使用的，是不是要加相关的路径到vimplus配置文件中？

**Comment by laiqb** [comment]
在.ycm_extra_conf.py中的flag中需要添加路径配置
