### ISSUE TITLE
安装出现错误，请解答一下

### ISSUE THREAD

**Issue by wohaoe** [chxuan/vimplus#132]
我的环境是Ubuntu18.04, vim8.0
完整错误如下：
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
BoostParts/CMakeFiles/BoostParts.dir/build.make:374: recipe for target 'BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/instances.cpp.o' failed
make[3]: *** [BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/instances.cpp.o] Error 4
make[3]: *** Waiting for unfinished jobs....
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
BoostParts/CMakeFiles/BoostParts.dir/build.make:302: recipe for target 'BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/cregex.cpp.o' failed
make[3]: *** [BoostParts/CMakeFiles/BoostParts.dir/libs/regex/src/cregex.cpp.o] Error 4
CMakeFiles/Makefile2:85: recipe for target 'BoostParts/CMakeFiles/BoostParts.dir/all' failed
make[2]: *** [BoostParts/CMakeFiles/BoostParts.dir/all] Error 2
CMakeFiles/Makefile2:152: recipe for target 'ycm/CMakeFiles/ycm_core.dir/rule' failed
make[1]: *** [ycm/CMakeFiles/ycm_core.dir/rule] Error 2
Makefile:131: recipe for target 'ycm_core' failed
make: *** [ycm_core] Error 2
ERROR: the build failed.

NOTE: it is *highly* unlikely that this is a bug but rather
that this is a problem with the configuration of your system
or a missing dependency. Please carefully read CONTRIBUTING.md
and if you're sure that it is a bug, please raise an issue on the
issue tracker, including the entire output of this script
and the invocation line used to run it.

**Comment by wohaoe** [comment]
我的gcc版本gcc-8

**Comment by wohaoe** [comment]
我的gcc版本是7.3.0啊，但是/usr/share/中只有gcc-8这个文件夹，没有gcc-7这个文件夹

**Comment by wohaoe** [comment]
我的gcc版本是7.3.0

**Comment by chxuan** [comment]
@wohaoe 可能你的系统内心不足了(c++: internal compiler error: Killed (program cc1plus))。

**Comment by chxuan** [comment]
@wohaoe 可能你的系统内存不足了(c++: internal compiler error: Killed (program cc1plus))。
