### ISSUE TITLE
Unable to start the ycmd server. Path in 'g:ycm_server_python_interpreter' option does not point to a valid Python 2.7 or 3.5+. Correct the error then restart the server with ':YcmRestartServer'.

### ISSUE THREAD

**Issue by xieqing0428** [chxuan/vimplus#135]
mac 10.14 使用`
conda create -n ycm python=3.5
`创造的python3.5环境也不适用，安装官网python3.5.4也报错……

**Comment by xieqing0428** [comment]
选择3.5环境打开日志ycmd_49835_stderr_a7uvw48g.log是空的

**Comment by chxuan** [comment]
@xieqing0428 首先你要确保ycm正确安装成功了。我的系统是mac 10.14.4，python版本是2.7.10使用ycm是没有问题的，如果有需要我也可以把我编译好的ycm发给你。

**Comment by xieqing0428** [comment]
唔，我用系统自带的python，提示The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). YCM core library compiled for Python 3 but loaded in Python 2. Set the 'g:ycm_server_python_interpreter' option to a Python 3 interpreter path
.



 <https://alessa0.cn/>	 	
From : 听泉.ღ
 
GitHub <https://github.com/xieqing0428> | Alessa0.cn <https://alessa0.cn/>
——夜如何其，夜未央，庭燎之光。
 

1、本电子邮件及其附件所载之信息均为不公开信息，仅供指定的收件人收阅。如果您错误地接收了本电子邮件，请立即回复并通知发件人，并永久删除该电子邮件及其所有附件和销毁所有复印件。2、未经发件人许可，请勿对本邮件内容进行披露、复制、分发或使用。对于任何由此造成的后果，发件人将保留法律追究的权利。3、互联网通信不能保证及时性、安全性、无差错或无病毒。发送者不对本邮件及附件中的任何错误或遗漏承担责任。  
1、The information in this email and any of its attachment is undisclosed. It is intended solely for the named addressee. If you have received this email in error, please reply to the sender and notify him/her of this immediately and permanently delete the email and all its attachments and destroy all copies of them. 2、Any disclosure, copying, distribution, or use of the contents of this email without the permission of the sender is prohibited. In the event of any consequence caused thereby, the sender reserves the right to take legal action. 3、The Internet communication does not guarantee timeliness, security, error-free or virus-free. The sender shall not be held responsible for any mistake or omission in the e-mail and attachments thereof.
