### ISSUE TITLE
如何设置自动添加信息和创建时间、作者？

### ISSUE THREAD

**Issue by Yengine** [chxuan/vimplus#137]
RT

**Comment by Yengine** [comment]
如何在.vimrc中修改？在网上找了几个都不能很好地解决。有的不能显示，或者显示错乱严重。
求解答

**Comment by chxuan** [comment]
@Yengine 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""新文件标题
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"新建.c,.h,.sh,.java文件，自动插入文件头 
autocmd BufNewFile *.cpp,*.[ch],*.sh,*.rb,*.java,*.py exec ":call SetTitle()" 
""定义函数SetTitle，自动插入文件头 
func SetTitle() 
	"如果文件类型为.sh文件 
	if &filetype == 'sh' 
		call setline(1,"\#!/bin/bash") 
		call append(line("."), "") 
    elseif &filetype == 'python'
        call setline(1,"#!/usr/bin/env python")
        call append(line("."),"# coding=utf-8")
	    call append(line(".")+1, "") 

    elseif &filetype == 'ruby'
        call setline(1,"#!/usr/bin/env ruby")
        call append(line("."),"# encoding: utf-8")
	    call append(line(".")+1, "")

"    elseif &filetype == 'mkd'
"        call setline(1,"<head><meta charset=\"UTF-8\"></head>")
	else 
		call setline(1, "/*************************************************************************") 
		call append(line("."), "	> File Name: ".expand("%")) 
		call append(line(".")+1, "	> Author: ") 
		call append(line(".")+2, "	> Mail: ") 
		call append(line(".")+3, "	> Created Time: ".strftime("%c")) 
		call append(line(".")+4, " ************************************************************************/") 
		call append(line(".")+5, "")
	endif
	if expand("%:e") == 'cpp'
		call append(line(".")+6, "#include<iostream>")
		call append(line(".")+7, "using namespace std;")
		call append(line(".")+8, "")
	endif
	if &filetype == 'c'
		call append(line(".")+6, "#include<stdio.h>")
		call append(line(".")+7, "")
	endif
	if expand("%:e") == 'h'
		call append(line(".")+6, "#ifndef _".toupper(expand("%:r"))."_H")
		call append(line(".")+7, "#define _".toupper(expand("%:r"))."_H")
		call append(line(".")+8, "#endif")
	endif
	if &filetype == 'java'
		call append(line(".")+6,"public class ".expand("%:r"))
		call append(line(".")+7,"")
	endif
	"新建文件后，自动定位到文件末尾
endfunc 
autocmd BufNewFile * normal G

**Comment by Yengine** [comment]
@chxuan 
多谢。但是我用了之后还是不起作用。
但是我找到了另外一种稍嫌麻烦的半自动方法。
模板还是你给的vimplus，在.vimrc中的末尾添加如下代码。其中第一行的F1可以任意替换为空白的F键。
在打开一个*.x文件之后，按下F1即可添加生成信息。
总之还是麻烦您了0.0



map <F1> :call TitleDet()<cr>
function AddTitle()
    call append(0,"/********************************************************")
    call append(1,"* Filename     : ".expand("%:t"))
    call append(2,"* Author       : Yengine ")
    call append(3,"* Last modified: ".strftime("%Y-%m-%d %H:%M"))
    call append(4,"********************************************************/")
    call append(5," ")
    call append(6," ")
    echohl WarningMsg | echo "Successful in adding copyright." | echohl None
endf

function UpdateTitle()
    normal m'
    execute '/# Last modified/s@:.*$@\=strftime(":\t%Y-%m-%d %H:%M")@'
    normal ''
    normal mk
    execute '/# Filename/s@:.*$@\=":\t".expand("%:t")@'
    execute "noh"
    normal 'k
    echohl WarningMsg | echo "Successful in updating the copyright." | echohl None
endfunction

function TitleDet()
    let n=1
    while n < 7
        let line = getline(n)
        if line =~ '^\#\s*\S*Last\smodified\S*.*$'
            call UpdateTitle()
            return
        endif
        let n = n + 1
    endwhile
    call AddTitle()
endfunction
