### ISSUE TITLE
打开文件的时候warning

### ISSUE THREAD

**Issue by Makmanfu** [chxuan/vimplus#143]
环境：ubuntu16.04 vim版本8.1

处理 function <SNR>115_PollServerReady[7]..<SNR>115_Pyeval 时发生错误:
行    4:
/home/docker/.vim/plugged/YouCompleteMe/third_party/requests_deps/reques
ts/requests/__init__.py:83: RequestsDependencyWarning: Old version of cr
yptography ([1, 2, 3]) may cause slowdown.
请按 ENTER 或其它命令继续
处理 function <SNR>115_PollServerReady[7]..<SNR>115_Pyeval 时发生错误:
行    4:
  warnings.warn(warning, RequestsDependencyWarning)

**Comment by pxlong** [comment]
我也出现同样的问题，@Makmanfu 您当时解决了吗？

**Comment by chxuan** [comment]
@pxlong 你好，你是通过最新的vimplus来安装的吗？

**Comment by pxlong** [comment]
@chxuan  是的，今天下午刚刚装的，我已经解决了，cryptography版本太老的问题，具体见 #185
