### ISSUE TITLE
希望能尽快支持openSUSE Leap系统

### ISSUE THREAD

**Issue by niaocaics** [chxuan/vimplus#157]
首先对各位付出表示感谢。我是一名openSUSE用户，现在系统版本为Leap 15.1。
我曾在CentOS 7的虚拟机试用过，感觉很棒，省去了安装插件过程中很多麻烦，希望能抽空增加对openSUSE Leap的支持，谢谢。

**Comment by chxuan** [comment]
@niaocaics 你好，感谢你使用vimplus，现在vimplus已经支持openSUSE了，尽情使用吧，有什么问题都可以问我。
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/6542180/61588611-3e1b4580-abd1-11e9-8971-91a675d2fd3b.png">

**Comment by niaocaics** [comment]
谢谢！没想到你能如此快的收到回复并得到改进，赞一个！
![2019-07-21 23-04-11屏幕截图](https://user-images.githubusercontent.com/31788564/61593163-8c9b0500-ac0e-11e9-8717-1d3bfe776201.png)

**Comment by niaocaics** [comment]
谢谢！没想到你能如此快的收到回复并得到改进，赞一个！已经开始用了，(*^__^*) 
![2019-07-21 23-25-57屏幕截图](https://user-images.githubusercontent.com/31788564/61593191-f0253280-ac0e-11e9-9001-0fc95932dd84.png)

**Comment by chxuan** [comment]
@niaocaics 目前在openSUSE上使用ycm来补全代码还有些问题，其他插件都可以正常使用。

**Comment by niaocaics** [comment]
谢谢提醒，我使用了一段时间也发现了。不过对我影响不是很大，我一般轻量的程序会用vim+插件来写，比较大的程序/项目还是会用IDE的。
