### ISSUE TITLE
about install.sh

### ISSUE THREAD

**Issue by tudouloveloli** [chxuan/vimplus#160]
```sh
# 安装mac平台字体
function install_fonts_on_mac()
{
    rm -rf ~/Library/Fonts/Droid\ Sans\ Mono\ Nerd\ Font\ Complete.otf
    cp ./fonts/Droid\ Sans\ Mono\ Nerd\ Font\ Complete.otf ~/Library/Fonts
}
```
作者您好，我看您也是中国人，就不用英语交流了。 嘿嘿。

1.  install.sh
请问这里直接删除Mac的文件， 是不是不太好。 可以先cp 为 Complete.otf.backup 然后在删除。方便在uninstall的恢复或者对原有文件不影响。
2. uninstall 
对于Linux平台卸载的建议就不说了。这里只说说Mac平台。
```sh
#!/bin/bash

sudo rm -rf ~/.vim

echo "Done!"
```
这里只是卸载了插件相关的东西。 
还是针对Mac平台。  我认为应该把字体文件恢复为原系统的文件。虽说这两文件好像没啥区别。嘻嘻。 安装时候的备份。 mv操作一下。这样是不是更好点。

**Comment by chxuan** [comment]
@tudouloveloli  你好，首先感谢你的建议，mac上原生是不带DroidSansMono这个字体文件的，除非用户自己安装了这个字体，卸载的话目前就只是简单的删除.vim文件夹，并没有卸载vimplus安装的软件(这些软件可能用户已经安装了)。

**Comment by tudouloveloli** [comment]
好的，感谢作者。
