### ISSUE TITLE
语法纠错功能，如何加入第三方库

### ISSUE THREAD

**Issue by orkfire** [chxuan/vimplus#161]
我需要用gtkmm编写ui，但是发现我include <gtkmm.h>,或是用到其它的一些gtkmm的变量或函数时，语法总是提示找不到函数定义或变量定义。但是编写时却能自动补全。如何告诉语法检测这个gtkmm的库的位置。

**Comment by chxuan** [comment]
@orkfire 如果都可以补全的话，那么语法检查应该不会出问题的，你补全第三方库修改ycm的配置没有？
<img width="890" alt="1" src="https://user-images.githubusercontent.com/6542180/62048244-f767c400-b23e-11e9-91f5-a37b48447901.png">

**Comment by orkfire** [comment]
> @orkfire 如果都可以补全的话，那么语法检查应该不会出问题的，你补全第三方库修改ycm的配置没有？
> <img alt="1" width="890" src="https://user-images.githubusercontent.com/6542180/62048244-f767c400-b23e-11e9-91f5-a37b48447901.png">

我没有修改YCM的配置文件，不知道怎么修改。
