### ISSUE TITLE
Ubuntu18.04LTS (WSL)下多次安装均失败

### ISSUE THREAD

**Issue by 2537194253** [chxuan/vimplus#163]
下载很慢重试了很多次,结果连 vim都没了.能告诉我怎么解决么,万分谢谢! [vim89比之前的好用么](url
![image](https://user-images.githubusercontent.com/37905552/62534343-80a07b80-b87b-11e9-95d8-099e3553fe4c.png)
)
Virtual packages like 'gvim' can't be removed

**Comment by chxuan** [comment]
@2537194253 你好，我没有在WSL版本的ubuntu18.04上测试过vimplus，但vimplus在ubuntu18.04上是能够正常安装的，建议你安装虚拟机来体验vimplus，由于ubuntu18.04的vim不支持python（不能使用ycm插件），所以执行install.sh时，该脚本会卸载系统的vim，然后下载最新的vim源码包来编译并支持python。

**Comment by 2537194253** [comment]
你好,感谢回复!其实我一直都在用你的神作,可是之前装了个shadow defender,VMware 15.1pro就崩了,无法启动虚拟机.卸载重装过好几次.只能是WSL了, 悲催.jpg~~~

**Comment by 2537194253** [comment]
我试了Centos(WSL) YCM编译成功了 ~/.vim/plugged/ 下的插件都生成了,可是vim命令却不能使用了,这可怎么办呀?

**Comment by 2537194253** [comment]
你好，感谢回复！其实我一直都在用你的神作，可是之前装了个影子后卫，VMware 15.1pro就崩了，无法启动虚拟机。卸载重装过好几次。只能是WSL了，悲催.JPG ~~~
我又试了Centos（WSL）YCM编译成功了〜/ .vim / plugged /下的插件都生成了，可是vim命令却不能使用了，这可怎么办呀？


------------------ 原始邮件 ------------------
发件人: "chxuan"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 晚上10:39
收件人: "chxuan/vimplus"<vimplus@noreply.github.com>;
抄送: "LGDKS"<2537194253@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [chxuan/vimplus] Ubuntu18.04LTS (WSL)下多次安装均失败 (#163)




@2537194253 你好，我没有在WSL版本的ubuntu18.04上测试过vimplus，但vimplus在ubuntu18.04上是能够正常安装的，建议你安装虚拟机来体验vimplus，由于ubuntu18.04的vim不支持python（不能使用ycm插件），所以执行install.sh时，该脚本会卸载系统的vim，然后下载最新的vim源码包来编译并支持python。

**Comment by 2537194253** [comment]
你好,不好意思再打扰下.我下了vim 在/user/bin/下操作才能用,能告诉我怎么解决么?
[root@LGDKS bin]# vi ~/.vimrc
-bash: /usr/bin/vi: No such file or directory
[root@LGDKS bin]# vim ~/.vimrc
LeaderF requires Vim 7.4.330+.
Press ENTER or type command to continue
[root@LGDKS bin]# vim ~/.vimrc
YouCompleteMe unavailable: requires Vim 7.4.1578+.
LeaderF requires Vim 7.4.330+.
Press ENTER or type command to continue![image](https://user-images.githubusercontent.com/37905552/62591411-12eb6280-b902-11e9-882c-d52ef418a45a.png)
这是没有添加环境变量的缘故么,还是要修改.vimrc?

**Comment by amchii** [comment]
@chxuan WSL下ubuntu 18.04LTS执行install.sh安装完成后vim会被卸载且未正常安装，执行`sudo apt install vim`安装后运行`vim`会提示以下报错信息
```
Error detected while processing /home/ubuntu/.vimrc:
line  109:
E117: Unknown function: plug#begin
line  111:
E492: Not an editor command: Plug 'chxuan/cpp-mode'
line  112:
E492: Not an editor command: Plug 'chxuan/vim-edit'
...
...
E492: Not an editor command: Plug 'rhysd/github-complete.vim'
line  150:
E492: Not an editor command: Plug 'vim-scripts/indentpython.vim'
line  152:
E117: Unknown function: plug#end
Press ENTER or type command to continue
```
按照.vimrc文件内容查看发现`~/.vim/plugged/`下只有YCM一个，我记得之前WSL ubuntu 16.04LTS是可以正常使用vimplus的。

**Comment by chxuan** [comment]
@amchii 你好，我没有在wsl版本的ubuntu上测试过，虚拟机的ubuntu16.04和18.04都可以正常安装，看上面的报错是因为在~/.vim/plugged/目录下没有找到相应的插件导致的，也就是说插件全部没有安装好，你是用的最新的vimplus安装的？

**Comment by amchii** [comment]
是的，使用git clone下载安装的 Heng Cao 邮箱：finethankuandyou@gmail.com 签名由 网易邮箱大师 定制 在2019年09月20日 13:46，chxuan 写道： @amchii 你好，我没有在wsl版本的ubuntu上测试过，虚拟机的ubuntu16.04和18.04都可以正常安装，看上面的报错是因为在~/.vim/plugged/目录下没有找到相应的插件导致的，也就是说插件全部没有安装好，你是用的最新的vimplus安装的？ — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by amchii** [comment]
@chxuan 是的，按照README使用git clone下载安装的

**Comment by chxuan** [comment]
@amchii 你可以再执行一次install.sh，除了ycm其他插件都没有安装成功，很大可能是因为plug.vim这个插件管理器没有下载下来，有什么问题你都可以问我（qq:787280310）
