### ISSUE TITLE
请支持Raspbian（树莓派OS）

### ISSUE THREAD

**Issue by stellarkey** [chxuan/vimplus#166]
RT
orz

**Comment by chxuan** [comment]
@stellarkey 你好，raspbian是32位系统，目前ycm只支持64位的系统。

**Comment by chxuan** [comment]
@stellarkey 如果要让ycm支持32位的系统，需要编译clang，等我有空的时候让vimplus树莓派。

**Comment by stellarkey** [comment]
谢谢大佬，了解了
