### ISSUE TITLE
安装完之后，运行vim碰到Error detected while processing function <SNR>115

### ISSUE THREAD

**Issue by pxlong** [chxuan/vimplus#185]
具体问题如下：
Error detected while processing function <SNR>115_PollServerReady[7]..<SNR>115_Pyeval:
line    4:
/home/xxx/.vim/plugged/YouCompleteMe/third_party/requests_deps/requests/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.

vimplus真是好用，感谢！

**Comment by pxlong** [comment]
找到解决方案了，是cryptography太老导致的，升级一下就行：
sudo pip install --upgrade cryptography
sudo python -m easy_install --upgrade pyOpenSSL

**Comment by chxuan** [comment]
@pxlong 好的哈，欢迎使用vimplus，有什么问题都可以问我。

**Comment by ksn13** [comment]
VMWare 安装的 UBUNTU 16.04
使用@pxlong的解决方案：
sudo pip install --upgrade cryptography
sudo python -m easy_install --upgrade pyOpenSSL
//==============================================
打开vim的时候会有如下错误：（敲2个回车，进入vim后也能正常使用）
error detected while processing function <SNR>118_PollServerReady[7]..<SNR>118_Pyeval:
line    4:
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
Press ENTER or type command to continue
Error detected while processing function <SNR>118_PollServerReady[7]..<SNR>118_Pyeval:
line    4:
  from cryptography import utils, x509
Press ENTER or type command to continue

**Comment by ksn13** [comment]
sudo vim /usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py
添加去除警告信息，可以解决问题
import warnings
warnings.filterwarnings('ignore')



> VMWare 安装的 UBUNTU 16.04
> 使用@pxlong的解决方案：
> sudo pip install --upgrade cryptography
> sudo python -m easy_install --upgrade pyOpenSSL
> //==============================================
> 打开vim的时候会有如下错误：（敲2个回车，进入vim后也能正常使用）
> error detected while processing function 118_PollServerReady[7]..118_Pyeval:
> line 4:
> /usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
> Press ENTER or type command to continue
> Error detected while processing function 118_PollServerReady[7]..118_Pyeval:
> line 4:
> from cryptography import utils, x509
> Press ENTER or type command to continue

**Comment by francioshu** [comment]
sudo apt install python-pip
sudo pip install --upgrade cryptography

vim ~/.vimrc
# 在vimrc加入下面这行代码告诉vim，ycm用的是python2.7
let g:ycm_server_python_interpreter = '/usr/bin/python2.7'
