### ISSUE TITLE
wsl Ubuntu18.04安装失败,无法下载插件

### ISSUE THREAD

**Issue by Kratos0902** [chxuan/vimplus#186]
[100%] Linking CXX shared library /home/kratos/.vim/plugged/YouCompleteMe/third_party/ycmd/ycm_core.so
[100%] Built target ycm_core
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (60) SSL: no alternative certificate subject name matches target host name 'raw.githubusercontent.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error detected while processing /home/kratos/.vimrc:                                                                    line  109:
E117: Unknown function: plug#begin
line  111:
E492: Not an editor command: Plug 'chxuan/cpp-mode'
line  112:
E492: Not an editor command: Plug 'chxuan/vim-edit'                                                                     line  113:
E492: Not an editor command: Plug 'chxuan/change-colorscheme'
line  114:
E492: Not an editor command: Plug 'chxuan/prepare-code'
line  115:
E492: Not an editor command: Plug 'chxuan/vim-buffer'
line  116:
E492: Not an editor command: Plug 'chxuan/vimplus-startify'
line  117:
E492: Not an editor command: Plug 'chxuan/tagbar'                                                                       line  118:
E492: Not an editor command: Plug 'Valloric/YouCompleteMe'
line  119:
E492: Not an editor command: Plug 'Yggdroot/LeaderF'
line  120:
E492: Not an editor command: Plug 'mileszs/ack.vim'
line  121:
E492: Not an editor command: Plug 'easymotion/vim-easymotion'                                                           line  122:
E492: Not an editor command: Plug 'haya14busa/incsearch.vim'
line  123:
E492: Not an editor command: Plug 'iamcco/mathjax-support-for-mkdp'
line  124:
E492: Not an editor command: Plug 'iamcco/markdown-preview.vim'
line  125:
E492: Not an editor command: Plug 'jiangmiao/auto-pairs'
line  126:
E492: Not an editor command: Plug 'scrooloose/nerdtree'
line  127:
E492: Not an editor command: Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
line  128:
E492: Not an editor command: Plug 'Xuyuanp/nerdtree-git-plugin'
line  129:
E492: Not an editor command: Plug 'godlygeek/tabular'
line  130:
E492: Not an editor command: Plug 'tpope/vim-fugitive'
line  131:
E492: Not an editor command: Plug 'tpope/vim-surround'
line  132:
E492: Not an editor command: Plug 'tpope/vim-commentary'                                                                line  133:
E492: Not an editor command: Plug 'tpope/vim-repeat'
line  134:
E492: Not an editor command: Plug 'tpope/vim-endwise'
line  135:
E492: Not an editor command: Plug 'octol/vim-cpp-enhanced-highlight'                                                    line  136:
E492: Not an editor command: Plug 'vim-airline/vim-airline'
line  137:
E492: Not an editor command: Plug 'vim-airline/vim-airline-themes'                                                      line  138:
E492: Not an editor command: Plug 'ryanoasis/vim-devicons'                                                              line  139: 
E492: Not an editor command: Plug 'junegunn/vim-slash'                                                                  line  140:
E492: Not an editor command: Plug 'junegunn/gv.vim'                                                                     line  141:
E492: Not an editor command: Plug 'kana/vim-textobj-user'                                                               line  142:
E492: Not an editor command: Plug 'kana/vim-textobj-indent'                                                             line  143:
E492: Not an editor command: Plug 'kana/vim-textobj-syntax'                                                             line  144:
E492: Not an editor command: Plug 'kana/vim-textobj-function'                                                           line  145:
E492: Not an editor command: Plug 'sgur/vim-textobj-parameter'                                                          line  146:
E492: Not an editor command: Plug 'Shougo/echodoc.vim'                                                                  line  147:
E492: Not an editor command: Plug 'terryma/vim-smooth-scroll'                                                           line  148:
E492: Not an editor command: Plug 'rhysd/clever-f.vim'                                                                  line  149:
E492: Not an editor command: Plug 'vim-scripts/indentpython.vim'                                                        line  151:
E117: Unknown function: plug#end
Press ENTER or type command to continue                                                                                         __                __
__   __/_/___ ___  ____  / /_  _______
\ \ / / / __ `__ \/ __ \/ / / / / ___/
 \ V / / / / / / / /_/ / / /_/ (__  )
  \_/_/_/ /_/ /_/ ,___/_/\____/____/
               /_/                     ...is now installed!

Just enjoy it!
p.s. Follow me at https://github.com/chxuan.

It takes 11 minutes.

**Comment by chxuan** [comment]
curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by chxuan** [comment]
上面报错大概意思是说通过curl来下载plugin.vim失败了，你可以尝试多次运行install.sh脚本试试

**Comment by chxuan** [comment]
我没有在wsl版本的系统里面测试过，不保证能正常安装成功，建议使用虚拟机安装系统来体验vimplus或者直接下载vimplus的docker版本来体验。

**Comment by Kratos0902** [comment]
确实是这样
我手动安装了plugin.vim，然后再在里面安装一下就好了

**Comment by chxuan** [comment]
@Kratos0902 好的，欢迎使用vimplus。
