### ISSUE TITLE
安装 indentLine 插无效

### ISSUE THREAD

**Issue by Titubery** [chxuan/vimplus#194]
[indentLine](https://github.com/Yggdroot/indentLine)是一个显示代码缩进的插件，我在~/.vimrc.local中添加了：
```
Plug 'Yggdroot/indentLine'
let g:indentLine_enabled = 0
```
安装后编辑文件却没有效果，你能看看是什么问题吗？
另：
1. 虽是终端编辑器，但和其他文件的交互也是难免的，可以考虑把和剪切板的交互映射为熟悉的`Ctrl+C`和`Ctrl+V`等；
2. 凑个数吧，默认的主题不太合眼，在local中安装主题貌似也不奏效。

**Comment by chxuan** [comment]
@Titubery 谢谢你的建议，增加插件还是要在~/.vimrc里面增加，比如说你要增加相对行号以及一些set类代码，可以在~/.vimrc.loal里增加，默认主题是否好看，不同的人会有不同的看法，欢迎使用vimplus。

**Comment by Titubery** [comment]
我不太喜欢改上游的东西，更新也许会出问题，再者这个插件对写python之类的还是比较好，用IDE或是notepad++/vscode之类的编辑器写c/c++也会有类似的缩进提示，希望老哥考虑考虑。主题其实挺好看的，只是背景颜色和我的终端不太一样，实际上也是添加自定义插件的问题。
另：gvim的字体设置格式有些问题，不同平台字体格式有区别。例如在Linux中你给的nerd字体：
![gvim](https://user-images.githubusercontent.com/17917040/67259528-e12d7500-f4c8-11e9-98fc-42fc9551abe7.png)
所以要设置为`set guifont=DroidSansMono\ Nerd\ Font\ Regular\ 18 `才会起效。（虽然我是为了剪切板才装的gvim，实际上不用）
thanks!

**Comment by chxuan** [comment]
@Titubery 我已经将Yggdroot/indentLine插件增加到默认.vimrc里并默认不开启，如果你要启用的话，你需要将let g:indentLine_enabled = 1增加到~/.vimrc.local里即可，我之前在deepin上安装gvim并使用该字体是可以的呢。

**Comment by chxuan** [comment]
@Titubery 我在ubuntu的gvim里面试试，因为目前vimrc里面设置的字体可以在macvim上使用，如果不能在linux上使用则需要分系统来设置了。

**Comment by chxuan** [comment]
@Titubery macvim和gvim的字体设置方式确实不一样，需要分系统设置，谢谢你提得建议，如果有什么好的想法，也可以给vimplus提pr，然后我来合并代码。

**Comment by Titubery** [comment]
好的，谢谢!
