### ISSUE TITLE
[Feature Request]关于帮助页面的小建议

### ISSUE THREAD

**Issue by Titubery** [chxuan/vimplus#197]
用起来比较顺手，一点小建议
1. 查看vimplus帮助文件，你用的：
`edit ~/.vimplus/help.md`
有点糙容易弄乱文件，可以考虑写个doc加到helptags里面，或者用：
`view +let\ &l:modifiable=0 ~/.vimplus/help.md`
view换sp能做到`:h *` 差不多的效果，但窗口高度需要再调
2. easymotion可以映射个`<leader>/`搜索快速跳转，当然这个可以自定义，凑数的；

**Comment by chxuan** [comment]
@Titubery 谢谢你的建议，你提的pr我已经合并了哈。

**Comment by Titubery** [comment]
好的，谢谢
