### ISSUE TITLE
[不是BUG/Feature Suggestions] 几点小小的建议

### ISSUE THREAD

**Issue by Titubery** [chxuan/vimplus#201]
1.  弄个更新脚本，用户不太知道更新了什么，pull之后往往会运行install。插件有plug管理，脚本负责更新字体、颜色之类vim-plug管不着的文件就好；
2.  虽然这个配置以c/c++为中心，但是应该考虑广泛些，现在可以自定义插件，核心配置可精简些，这样用户选择面会更宽些，vim-plug的on/for之类的参数也可以加上提高性能，反正轻量就完事了；
3. 还有一个无关紧要的是vimplus-startify，logo下面一般跟slogan，其实也可以搞像签名之类的自定义，联系方式什么的可以贴到帮助页面😄️，就像一般软件的about页面一样；
4. 还可以把文档之类的翻译哈，这个就更无所谓了，扩大潜在用户群体而已。最近没时间不然可以帮着搞一下；
5. 抛弃Python2，拥抱Python3🙃️（凑数
以上，谢谢。

**Comment by chxuan** [comment]
@Titubery 首先谢谢你提得建议，下面我做下解答哈：
1.更新脚本主要是做什么工作呢？我想的是直接git pull更新了vimplus的仓库，如果熟悉一点git的用户可以直接git log filename来看更新了什么，如果增加更新脚本可以更方便用户，那当然可以。
2.现在vimplus确实目前已c/c++为主，ycm也主要支持c/c++，如果要增加其他语言的话，不同系统，不同语言都需要测试，工作量很大，而且很容易出bug，所以vimplus目前还只支持c++，vimrc里的插件确实可以减少一些，但有些还是必须保留，比如说vim-easymotion,auto-pairs,vim-slash,vim-commentary等能够让编辑、光标移动更顺畅的插件。
3.确实还少一个标语，但标语之类的还没有想好😄️，想好了再加。。
4.之前想过要把文档翻译成英文，但考虑到我英文水平有限而且用户基本为中国人，所以就没有实施
5.之前编译ycm的时候默认使用python2.7编译，后来有用户反馈新的centos8以及mac10.15已经默认支持python3了，python2可能会废弃掉，所以python3是趋势，我之前都统一用python2，有两个原因，一是代码比较容易维护，二是在有些系统里使用python3来编译ycm会报错，所以现在我将编译ycm使用python2还是python3抛给了用户，让用户选择，目前安装脚本里只有在某些系统编译vim的时候使用python2，后面可以考虑改成python3
6.这个是我自己加的，还可以给vimplus建立一个网站（主要用于装逼😄️），参考网站：http://spacemacs.org/和https://spacevim.org/，但目前还不会考虑建立微信群、qq群之类的，主要是我不想维护这些群以及不想过度宣传。

**Comment by Titubery** [comment]
也对，应该相信用户。脚本的话确实必要性不大，好像只有字体直接pull下来还要复制一下；
没必要支持多语言，需要的可以自己加；
核心编辑的功能当然要保留，插件可以按文件类型/命令加载，vim-plug支持这个；
英文的话想来也没有太大的必要；
python2明年好像就停止支持了；
说标语的话，我想到fish的greeting，安装后第一件事就是把它给换掉😄️；
那两space*总给我一种有点重的感觉，还是喜欢轻量的，QQ群没什么意思，不过最近LinuxQQ好像死灰复燃了，tg群可以；
以上 @chxuan

**Comment by chxuan** [comment]
@Titubery 增加一个更新脚本还是有必要的，我已经增加了，我没有用过vim-plug插件管理器按文件加载插件的功能，我想的是插件作者可以保证该插件是否在某个特定文件类型加载，我之前写的几个插件也是这么实现的。
