### ISSUE TITLE
wsl下翻页操作背景会变成黄色

### ISSUE THREAD

**Issue by XQDD** [chxuan/vimplus#206]
### wsl窗口、vs code、idea下可复现
![image](https://user-images.githubusercontent.com/20871761/68088426-2161ff80-fe9a-11e9-8358-acdadab3b3f0.png)

![image](https://user-images.githubusercontent.com/20871761/68088433-30e14880-fe9a-11e9-8fa8-218d460aeafe.png)

![image](https://user-images.githubusercontent.com/20871761/68088437-3ccd0a80-fe9a-11e9-9903-5dffd85c5185.png)

### XShell, Windows Terminal (Preview)下正常

![image](https://user-images.githubusercontent.com/20871761/68088473-99c8c080-fe9a-11e9-8421-1df0be749aaf.png)

![image](https://user-images.githubusercontent.com/20871761/68088475-9cc3b100-fe9a-11e9-86aa-955636b545de.png)

**Comment by chxuan** [comment]
@XQDD 这个应该和本身终端字符集、颜色位色有关。

**Comment by XQDD** [comment]
OK，找到了，这个issue中有提到多种解决方案
https://github.com/microsoft/terminal/issues/832#issuecomment-493747616
