### ISSUE TITLE
推荐给仓库打个release版本

### ISSUE THREAD

**Issue by jason416** [chxuan/vimplus#207]
在变化或者添加新功能前打个标签，以免遇到问题，还能退回以前的稳定版本使用，等问题解决在更新。

**Comment by chxuan** [comment]
@jason416 你好，谢谢你的建议，目前vimplus还没有所谓的一个稳定版本，因为在不同的系统，不同的使用环境，不敢保证这个版本没有问题，vimplus提交代码大部分是修改bug，之前的版本肯定也是不稳定的（正常情况下git clone的版本是最稳定的）。

**Comment by jason416** [comment]
~好吧。我用加入update功能前的版本正常使用，更新过后，就出现了 #208 提示。就想看下有没有正式版，发现没有^_^。没事，辛苦了~！

**Comment by chxuan** [comment]
@jason416 你说的更新是指使用update.sh更新，还是git pull更新vimplus的仓库代码，然后重新安装？，如果是用update.sh更新的话，看update.sh里的代码就知道，应该不会出现#208上的问题，因为update.sh更新其实就是拉取最新的vimplus，然后更新下插件（ycm不会更新的，其他插件会更新），所以说update.sh更新应该不会影响到ycm的使用，如果是更新了vimplus代码，然后重新执行install.sh的话，ycm的安装逻辑以及ycm在gitee上的代码最近都是没有变动的，唯一改动的就是vimplus的vimrc里对于python解释器路径的配置：let g:ycm_server_python_interpreter = '/usr/bin/python2.7'，我将该配置注释掉了，ycm会自动去查找合适的python解释器（与编译ycm时使用的python版本匹配），如果你显示指定python解释器路径看可不可以解决你在#208上遇到的问题。

**Comment by chxuan** [comment]
@jason416 vimplus不像一般的软件一样，一般的软件只要保证代码质量以及足够的测试，就能够保证版本的稳定，但vimplus不是这样的，因为不同的用户，使用的系统不一样，默认环境也不一样，就算在相同的系统版本上，A用户安装没有问题，B用户安装可能就会出现问题，所以说vimplus就没有release版本的概念。

**Comment by jason416** [comment]
了解，辛苦了！

**Comment by jason416** [comment]
> @jason416 你说的更新是指使用update.sh更新，还是git pull更新vimplus的仓库代码，然后重新安装？，如果是用update.sh更新的话，看update.sh里的代码就知道，应该不会出现#208上的问题，因为update.sh更新其实就是拉取最新的vimplus，然后更新下插件（ycm不会更新的，其他插件会更新），所以说update.sh更新应该不会影响到ycm的使用，如果是更新了vimplus代码，然后重新执行install.sh的话，ycm的安装逻辑以及ycm在gitee上的代码最近都是没有变动的，唯一改动的就是vimplus的vimrc里对于python解释器路径的配置：let g:ycm_server_python_interpreter = '/usr/bin/python2.7'，我将该配置注释掉了，ycm会自动去查找合适的python解释器（与编译ycm时使用的python版本匹配），如果你显示指定python解释器路径看可不可以解决你在#208上遇到的问题。

我试过显示指定解释器路径，未解决该问题。
