### ISSUE TITLE
[Question] 需不需要一个卸载/关闭默认插件的功能？

### ISSUE THREAD

**Issue by Titubery** [chxuan/vimplus#212]
本来想改改开始界面但好像vimplus-startify不支持vim-startify的一些函数。为了不动vimrc搬了个unplug函数。考虑到这功能几乎没人需要，问问你觉得有必要我可以提个pr

**Comment by chxuan** [comment]
你的意思说如果~/.vimrc里有默认的插件prepare_code，但用户又不想启用这个插件吗？我想的是可以这样，一般插件作者在插件开头都会这样定义
![image](https://user-images.githubusercontent.com/6542180/69239306-e0295980-0bd4-11ea-9ef5-162cb85ee6ca.png)
，然后如果不想启用该插件，可以在~/.vimrc.config里加入let g:prepare_code = 1就可以了，但这样做只是做到不启用该插件，但并不能卸载。

**Comment by Titubery** [comment]
所以我说这个基本没人要，因为我提的这俩共用了一些函数名配置冲突不得不卸载。关闭的话我知道有这么些选项
