### ISSUE TITLE
YCM在c++中没有for,if这些关键字,而且出现不补全菜单,无法选择,只有按右侧方向键才能选择

### ISSUE THREAD

**Issue by hkj1842** [chxuan/vimplus#220]
YCM在c++中没有for,if这些关键字,而且出现不补全菜单,无法选择,只有按右侧方向键才能选择

主要是没法确认所选项目,tab键是向下选

**Comment by chxuan** [comment]
for,if不需要补全，我一般使用tab来选择。

**Comment by chxuan** [comment]
shift+tab向上选择

**Comment by hkj1842** [comment]
tab是向下,shift是向上,没有确认吗,因为补全后,补全菜单还是存在,我设置let g:ycm_autoclose_preview_window_after_completion = 1 也不顶用

**Comment by chxuan** [comment]
比如说你补全printf()这个函数，当你的tab键选中printf的时候，补全菜单并不会消失，然后当你按下(的时候，补全菜单就消失了。

**Comment by hkj1842** [comment]
是的,这样我很不习惯,既然就是这样我就适应下把
