### ISSUE TITLE
安装脚本中用软连接的方式更方便升级

### ISSUE THREAD

**Issue by dofy** [chxuan/vimplus#23]
软连接的方式是参考了 [ivim](https://github.com/kepbod/ivim) 这个项目，因为有了个性化配置文件，用户不再需要修改 `.vimrc` 文件，这样后期升级就只更新项目中的文件即可，更新后运行 `:PluginUpdate`，不会影响用户的自定义内容。

**Comment by chxuan** [comment]
@dofy 自定义文件那个我知道，但是软连接用在这里的好处是什么呢？用户clone了vimplus并且安装之后，vimplus可能就被用户删除了，软链接就找不到原始文件了，除非克隆的时候就指定成隐藏文件~/.vimplus，这样用户就不会删除了，不知道我表达的对不对。

**Comment by chxuan** [comment]
@dofy 谢谢你提得pr，有什么好的意见或建议都可以提的，谢谢！

**Comment by dofy** [comment]
`ivim` 的做法是分为安装和升级：
- 安装是把项目文件 `clone` 到 `~/.ivim` 下，用软连接到方式把项目目录下的  `.vimrc` 和 `.vimrc.local` 等一系列文件放到 `~` 下
- 升级脚本执行的流程简单说就是，`pull` 项目文件，执行 `:PluginUpdate`

这样的好处有二：一是可以避免项目更新后还要重新安装一遍（删掉 `.vim` 重新安装又需要很长时间），二是避免覆盖掉用户自定义配置。

**Comment by chxuan** [comment]
@dofy 非常感谢你的回复，现在vimplus已经已经支持软链接方式安装了！

**Comment by dofy** [comment]
不用客气，非常棒的配置，希望更多人了解这个项目，有幸能一起完善他 😁
