### ISSUE TITLE
可以看看为啥这个QFGrep(https://github.com/sk1418/QFGrep)插件用不了吗

### ISSUE THREAD

**Issue by Bluekezhou** [chxuan/vimplus#232]

**Comment by Bluekezhou** [comment]
或者是vim-qf ?
我已经用Plug 'romainl/vim-qf' 加载插件了，但是找不到对应的命令

**Comment by chxuan** [comment]
@Bluekezhou 你安装没有呢？

**Comment by Bluekezhou** [comment]
用PlugInstall安装了的，但是感觉像是有一段代码没有加载上来，但我对vim脚本不是很了解

**Comment by Bluekezhou** [comment]
就比如装了vim-qf，doc可以正常加载，使用help也可以正确索引，但像什么Reject之类的命令就没有

**Comment by chxuan** [comment]
@Bluekezhou 这个应该是插件自身的问题撒，你可以去看下vim-qf的使用教程呢
