### ISSUE TITLE
无法安装vim-clang-format插件

### ISSUE THREAD

**Issue by fisherboys** [chxuan/vimplus#235]
1、在.vimrc.custom.plugins文件中增加了Plug 'vim-clang-format'
2、运行./update.sh
3、提示[vim-plug] Invalid argument: vim-clang-format (implicit `vim-scripts' expansion is deprecated)。

请问：安装插件的具体流程是怎样的？

**Comment by chxuan** [comment]
@fisherboys 你好，vimplus使用vim-plug（https://github.com/junegunn/vim-plug）来进行插件管理，你可以是使用:PlugInstall来安装插件，update.sh是vimplus代码仓库的更新脚本，vimplus常用命令可以通过,h命令来查看，欢迎使用vimplus
