### ISSUE TITLE
crontab问题

### ISSUE THREAD

**Issue by happinesslijian** [chxuan/vimplus#236]
当我安装完vimplus的时候编辑任何后缀的文件都正常但是使用命令crontab -e提示如下：
```
[root@k8s-node2 .vimplus]# crontab -e
no crontab for root - using an empty one
/bin/sh: /usr/bin/vi: 没有那个文件或目录
crontab: "/usr/bin/vi" exited with status 127
```
这问题该怎么解决呢？十万火急！求助！ @chxuan

**Comment by happinesslijian** [comment]
我发现了新问题vimplus这个项目存在重大bug！不仅仅是crontab使用不了，edit命令也无法使用了！
我使用virsh edit mydomain 也出现问题！我的环境是centos7.6 卸载该vimplus项目也不行！求助！ @ @chxuan @dofy @starifly @zhoumengkang

**Comment by chxuan** [comment]
@happinesslijian 你好，欢迎使用vimplus，vimplus在centos7上面安装的时候会把自带的vi编辑器卸载，然后通过源码编译安装vim，让vim支持python模块，以便可以正常使用ycm，在使用crontab的时候确实没有考虑到这个问题，其实你可以通过设置一个软链接来解决ln -s /usr/bin/vim /usr/bin/vi，或者其实执行crontab也是调用vi编辑器去修改crontab的配置文件，那么你可以直接使用vim /etc/crontab命令来修改也是可以的。

**Comment by chxuan** [comment]
@happinesslijian 如果你执行virsh edit mydomain去修改配置文件的话，当执行virsh edit的时候如果它也是去调用/usr/bin/vi命令的话，那也可以通过设置软链接来解决ln -s /usr/bin/vim /usr/bin/vi

**Comment by chxuan** [comment]
@happinesslijian 目前的情况来看就是有些依赖vi的软件，去调用vi命令找不到，因为vimplus已经将vi卸载，然后安装了vim，通用做法就是设置软链接，谢谢你反馈的这个问题，我马上修复一下，在安装脚本里设置

**Comment by happinesslijian** [comment]
您好，感谢收到了您的回复，我尝试做软连接了 是可行的！
但是还是希望您可以整改安装脚本保留系统默认自带的vi编辑器！因为系统本身很多程序都是依赖vi编辑器的而不是依赖vim编辑器！
建议在保留系统自带的vi编辑器的前提下进行安装部署vim及其插件
再次感谢！ @chxuan @chxuan

**Comment by chxuan** [comment]
@happinesslijian 感谢你提的意见，目前不清楚vi和vim同时存在有没有问题，我先尝试下。

**Comment by happinesslijian** [comment]
您先测试一下试试看吧。我提的建议如下：
1. 最好还是把系统自带vi编辑器保留下来，不要覆盖安装。（vi编辑器是vi编辑器 vim编辑器是vim编辑器 两者不要冲突 保持可以运行在同一个操作系统内）
2. 如果第1条做不到建议不要让使用人手动创建软连接 `ln -s /usr/bin/vim /usr/bin/vi` 来解决我上面发生的问题，建议写到脚本里（也算脚本优化一下），当用户使用命令crontab -e 或者 edit的时候不要出现错误。
以上就是我的两条提议，感谢您的聆听！

**Comment by chxuan** [comment]
@happinesslijian 你好，目前测试没有发现问题，vi和vim可以共存，并且系统有老版本的vim，我通过编译安装vim后会覆盖掉老版本的vim，所以不需要卸载系统原有的vi和vim，你的建议很好，我已经将你加入vimplus贡献者列表了。

**Comment by chxuan** [comment]
@happinesslijian 测试发现通过crontab -e会报如下错误
![image](https://user-images.githubusercontent.com/6542180/75089938-c06d4d00-5598-11ea-850d-3d0f0d7c481f.png)
应该是vi并不认识~/.vimrc里面的配置，但并不影响vi的正常使用

**Comment by happinesslijian** [comment]
十分感谢您把我加入该项目的贡献者，我在此表示感谢！
没错，我当时的报错也是这样的，只不过我没截图说明！
那您经过这一次的测试后，最终的解决办法就是创建软连接吗？如下命令：
`ln -s /usr/bin/vim /usr/bin/vi`
如果是的话,那请问您有没有对现有的`install.sh`或者`update.sh`安装脚本进行优化呢？

**Comment by chxuan** [comment]
@happinesslijian 你好，我已经优化了vimplus的脚本并提交到仓库了哈，目前的方案是不卸载原有系统的vi和vim，vi和vim共存的方案，只是使用vi命令的时候，会出现加载~/.vimrc不识别里面的某些配置，报错之后按enter键即可正常使用vi，所以也就没有将ln -s /usr/bin/vim /usr/bin/vi命令加入vimplus脚本了，因为vi也不怎么常用，如果加了软链接，那基本上就用不了vi了，那和之前卸载vi也没什么两样，如果用户要消除这个报错，也可以自己手动执行该软链接命令，我在vimplus的readme上都会说明。

**Comment by happinesslijian** [comment]
好嘞，明白您的意思了。我即将关闭这个问题 @chxuan 感谢您的回复
