### ISSUE TITLE
在开启NerdTree的情况下，<leader>d功能异常

### ISSUE THREAD

**Issue by Virus-V** [chxuan/vimplus#244]
在开启NerdTree的情况下，关闭buffer导致整个vim界面只剩下一个NerdTree界面，右边的代码界面消失，上面导航栏面对应buffer并未关闭。关闭NerdTree后正常可关闭buffer。

复现方法：
1. 通过NerdTree打开多个buffer
2. 保持NerdTree窗口开启，激活任意一个buffer，按<leader>d快捷键关闭该buffer

**Comment by chxuan** [comment]
@Virus-V 该功能是vim-buffer插件提供的，该插件调用:bd命令来关闭一个buffer，我打开两个buffer并且在有nerdtree的情况下执行命令:bd关闭掉一个buffer，最终效果也是只剩下nerdtree，最好还是在关闭nerdtree的情况下关闭各个buffer

**Comment by Virus-V** [comment]
好的，了解了，谢谢回复！
