### ISSUE TITLE
指定python运行环境必须在首行

### ISSUE THREAD

**Issue by applejwjcat** [chxuan/vimplus#245]
例如 #!/usr/bin/env python3 必须位于首行，否则会报错，但默认生成的代码块不在首行

**Comment by chxuan** [comment]
@applejwjcat 是在行首的啊
![image](https://user-images.githubusercontent.com/6542180/77020791-e16e6580-69bf-11ea-87f0-9d302b32f89f.png)

**Comment by applejwjcat** [comment]
@chxuan 哦哦，不好意思，我加了文件注释头（生成时间，作者），然后就报错了。我自己再改改吧
