### ISSUE TITLE
安装zsh后，vim的文件内容提示好像没有了

### ISSUE THREAD

**Issue by applejwjcat** [chxuan/vimplus#249]
难道vinplus换了shell后需要重新配置吗？按理说不用阿，不就是改变了bashrc吗？希望作者回答一下

**Comment by applejwjcat** [comment]
这是source .vimrc后的输出
   .  . .  .  . .  . S@t.. .  .  . .  .  . .  .  . .  .  . .  .  . .  .  . .  .  . .  .  . .  .  . .  .  . .  .  . .  ..
：未找到命令
t.X8S%：未找到命令
      . %St8;8:X;8:8:8%8;%%:@S:    . .    . .    ....    .  .    .  .    .  .    .  .    .  .    .  .    .  .    .  ....
：未找到命令
t：未找到命令
S：未找到命令
bash: fg: %@88:X.8X8%: 无此任务
8S：未找到命令
    ..X.;X%8t8%8ttX.88;8.8%:;% ;8:SX%.   SX.8S.  St88:  .  .   .  .    ..XS.@%SSS88S@:. X@@%  . . .    .  .    .  ......
：未找到命令
8SS888：未找到命令

Command '8tt' not found, did you mean:

  command 'btt' from deb blktrace
  command 'mtt' from deb xawtv
  command 'tt' from deb treetop

Try: sudo apt install <deb name>

8:8:8：未找到命令
t:t8S：未找到命令
.%SSSSSSSS%.：未找到命令
    :t8 :;X8S;8.8S;8S.8.t8:%8XS.. S8.8:.S8;8;  :@;@88 . S:88 X.88@88:@t..%S.  .. X;8@: :%:;8. X%:X;. 8;.;  %S8@XXSXSS8..
：未找到命令
/usr/lib/xorg/Xorg.wrap: Only console users are allowed to run the X server
8S8888：未找到命令
8S8t：未找到命令
@8X：未找到命令
8t8:..S.S@%SSS8S88t：未找到命令
X:.X.：未找到命令
  8; :888XSStS;88;88X%;;tt::;;8@ ..%X88:88Xt    .S@.::. S@8% X8.@;S888X .%;88SSSS.SX.:. 8S88: @;88t. 8.S8  t;@8@88@88S..
：未找到命令
bash: fg: %8S8: 无此任务
8888：未找到命令
t8.8S：未找到命令
.:....：未找到命令
..8888:..8:8@:：未找到命令
St@@888.@@..：未找到命令
bash: .vimrc: 行 12: 未预期的符号 `;;' 附近有语法错误
bash: .vimrc: 行 12: `"    t.8XX;;8X% XX.  .    %8X8;   . :tX8@t     .  t8X8:  %@@S X8@@:t8tXt...:%t..       . X:8X  X8@@88@888t. %88t888 888t.'

**Comment by chxuan** [comment]
你好，换了shell应该是不会影响vimplus的使用的，我目前也在用zsh，现在vimplus用不了主要是提现在哪些方面呢？还有就是你不能去source vim的配置文件。

**Comment by applejwjcat** [comment]
哦哦，我在custom里定义了一些shell命令，失效了，我该过来就好了
