### ISSUE TITLE
安装ultisnips出错

### ISSUE THREAD

**Issue by applejwjcat** [chxuan/vimplus#250]
我在自己简单的vim+vimplug上安装这个插件没问题，可是用您的vimplus去安装就有问题，您可以试一下看看是不是插件有冲突？这是一个自定义代码片段的插件

**Comment by applejwjcat** [comment]
就是打开一个文件插入的时候会报错：
处理 InsertCharPre 自动命令 "*" 时发生错误:
E117: Unknown function: UltiSnips#TrackChange

**Comment by chxuan** [comment]
@applejwjcat 这个报错并不是冲突导致的，就是没有找到该函数，你可以去比较下两个的代码，是否有UltiSnips#TrackChange函数
