### ISSUE TITLE
Python头部注释怎么修改

### ISSUE THREAD

**Issue by Eloco** [chxuan/vimplus#255]
vim .py文件会自动生成头部注释

请问我应该去哪修改或者删除默认头部呢

**Comment by chxuan** [comment]
@Eloco 你好，感谢你使用vimplus，自动生成文件头是prepare-code (https://github.com/chxuan/prepare-code)提供的，你可以修改该代码模板来满足你的需求

**Comment by chxuan** [comment]
@Eloco 你好，感谢你使用vimplus，自动生成文件头是prepare-code (https://github.com/chxuan/prepare-code) 提供的，你可以修改该代码模板来满足你的需求
