### ISSUE TITLE
Error detected while processing function <SNR>125_on_timer

### ISSUE THREAD

**Issue by yjblog** [chxuan/vimplus#258]
![图片](https://user-images.githubusercontent.com/46447440/79092468-9d367100-7d83-11ea-8476-d21e43e8a83b.png)
进入--insert--模式后，输入任意内容都会出现这个错误，怎么解决啊，朋友们

**Comment by ChengLong777** [comment]
同问

**Comment by kmeng1989** [comment]
同问
