### ISSUE TITLE
CentOS 7 使用sudo打开vi，配置没有被加载

### ISSUE THREAD

**Issue by istanggsh** [chxuan/vimplus#276]

**Comment by chxuan** [comment]
@istanggsh 你使用sudo vim来打开文件试试，centos下，vim和vi不是同一个软件

**Comment by istanggsh** [comment]
sudo vim也不行，我已经把vi和vim设置为同一个了，还有在ubuntu20也是sudo不加载配置

**Comment by applejwjcat** [comment]
You can make the softlink of vimrc in the root directory, because sudo use the root config

**Comment by applejwjcat** [comment]
你可以让root用户加载vimplus配置，就可以了

**Comment by applejwjcat** [comment]
也可以alias sudo="sudo "
