### ISSUE TITLE
在使用拷贝函数声明快捷键(,y)时 , 出现如下错误

### ISSUE THREAD

**Issue by Visual-studio-star** [chxuan/vimplus#278]
![image](https://user-images.githubusercontent.com/59254083/87000272-40fab600-c1e7-11ea-8fa4-b92a7d863b17.png)

**Comment by chxuan** [comment]
@Visual-studio-star 你好，请问你的源代码是什么格式呢？

**Comment by Visual-studio-star** [comment]
> @Visual-studio-star 你好，请问你的源代码是什么格式呢？

C++
![image](https://user-images.githubusercontent.com/59254083/87056861-c9557700-c238-11ea-8827-20be4be8fa7c.png)

**Comment by Visual-studio-star** [comment]
> @Visual-studio-star 你好，请问你的源代码是什么格式呢？

函数的声明 与 定义 在同一个cpp中

**Comment by chxuan** [comment]
@Visual-studio-star 函数生成是cpp-mode （https://github.com/chxuan/cpp-mode）插件提供的，目前该插件不支持类外定义的函数

**Comment by Visual-studio-star** [comment]
> @Visual-studio-star 函数生成是cpp-mode （[https://github.com/chxuan/cpp-mode）插件提供的，目前该插件不支持类外定义的函数](https://github.com/chxuan/cpp-mode%EF%BC%89%E6%8F%92%E4%BB%B6%E6%8F%90%E4%BE%9B%E7%9A%84%EF%BC%8C%E7%9B%AE%E5%89%8D%E8%AF%A5%E6%8F%92%E4%BB%B6%E4%B8%8D%E6%94%AF%E6%8C%81%E7%B1%BB%E5%A4%96%E5%AE%9A%E4%B9%89%E7%9A%84%E5%87%BD%E6%95%B0)

此格式下 函数声明的跳转(偶尔) 和 函数实现的跳转 都会失效也是这个原因吗

**Comment by chxuan** [comment]
@Visual-studio-star 是的哈，同一文件跳转可以通过`ctrl + *`光标所在单词来查找也很方便

**Comment by Visual-studio-star** [comment]
> @Visual-studio-star 是的哈，同一文件跳转可以通过`shift + *`光标所在单词来查找也很方便

感谢
