### ISSUE TITLE
archlinux中C++里cout总是报错

### ISSUE THREAD

**Issue by applejwjcat** [chxuan/vimplus#280]
例如：no member named 'cout' in namespace 'std'
是哪个插件除了问题？
我重新安装纯净版还是这样，但在ubuntu和Centos上没有遇见

**Comment by chxuan** [comment]
@applejwjcat 你好，安装vimplus时，特别是编译ycm时报错么有呢？

**Comment by applejwjcat** [comment]
谢谢你，应该是之前我不小心删掉了python的某个库，我今天找了半天也没找到。只好把ycm改成coc，把你的vimplus移植到neovim还是蛮容易的，而且非常好用

**Comment by applejwjcat** [comment]
哈哈，删掉的库又被我找回来了，我又可以用vimplus了。谢谢作者！我从你的代码中受到了很多启发
