### ISSUE TITLE
关于leaderf配置的一点建议

### ISSUE THREAD

**Issue by applejwjcat** [chxuan/vimplus#281]

**Comment by applejwjcat** [comment]
在配置中.vimrc里<leader>f 被映射成:LeaderfFile ~<cr>
而当我进入其他目录时，再打开<leader>f,就会出现下面这种情况：
Exception('/bin/sh: line 0: cd: /home/appledog/~: No such file or directory\n')
我觉得应该是:LeaderfFile 应该是在当前目录下搜索
也许是其他问题导致，你觉得呢？

**Comment by chxuan** [comment]
@applejwjcat 你好，感谢你提的建议，之前的配置是没有问题的，是leaderf代码更新后没有考虑到之前接口的兼容性，我现在修改成了默认搜索当前目录，欢迎使用vimplus。
