### ISSUE TITLE
不建议安装这个. 甚至不建议安装任何vim插件. 

### ISSUE THREAD

**Issue by duzefu** [chxuan/vimplus#288]
你会遇到: 
1.文件内有乱码的话,VIM就会不断报错完全不能用. 
2.就算没有乱码,也会有概率因为各种莫名其妙的代码补全插件出错,或者其他插件出错导致不断报错,几乎不能用

点名YCM,不能稳定运行=辣鸡

**Comment by chxuan** [comment]
@duzefu 你可以试试docker版本的vimplus

**Comment by duzefu** [comment]
1.经过一堆坑之后，终于弄好了，建议直接用conda作为python环境来安装，免得出现各种python版本冲突的问题。
2.YCM需要配置之后，自定义的头文件才能补全，具体谷歌
