### ISSUE TITLE
只能安装在root下，不能安装在用户下，是怎么回事？求助大佬

### ISSUE THREAD

**Issue by jacksparrowwang** [chxuan/vimplus#29]
ycm不支持7.4.160版本vim，我把vim升级到8.0后只能在root下用，然后我让用户下的vim指向了root下的vim，然后安装vimplus只能在root下用，好像也只能安装在root下，就是当输入sudo ./install.sh 自动就跑到root/.vim/下面去安装了。我该怎么搞到用户下面

**Comment by chxuan** [comment]
@jacksparrowwang 请问你的是什么系统，如果是非root用户安装也应该在home/you_user_name/下啊

**Comment by jacksparrowwang** [comment]
我的是CentOS，我发现我在装系统的时候，有个磁盘划分，我添加了一个/home磁盘到数据盘，然后就不行了。我只要在划分磁盘的时候，按照系统默认的来，升级vim8.0后，装vimplus就装到用户下了。我自己安装了好几次，试出来应该是这个原因~     大佬知道是什么原因吗？还是我这么想有问题。

**Comment by jacksparrowwang** [comment]
我的是CentOS，我发现我在装系统的时候，有个磁盘划分，我添加了一个/home磁盘到数据盘，然后就不行了。我只要在划分磁盘的时候，按照系统默认的来，升级vim8.0后，装vimplus就装到用户下了。我自己安装了好几次，试出来应该是这个原因~ 大佬知道是为什么吗？还是我这么想有问题。
