### ISSUE TITLE
关于YCM自动检查

### ISSUE THREAD

**Issue by xht19980305** [chxuan/vimplus#291]
### 如何设置 YCM 检查在大型项目里

![image](https://user-images.githubusercontent.com/24425182/90209928-37d0ba80-de1f-11ea-9edf-49c302474bac.png)
如图 关注 48 行/ 61 行

原先使用VIm的时候在项目里配置好.ycm_extra_conf.py 即可正常检查

**Comment by chxuan** [comment]
@xht19980305 你好，谢谢你的支持，感谢你使用vimplus，你上面的表述，我没怎么看懂呢，vimplus安装好后是可以进行c++的代码补全和语法检查的，默认是不需要修改.ycm_extra_conf.py的。

**Comment by xht19980305** [comment]
上面图片的第48行 没有进行自动检查并报错。

**Comment by chxuan** [comment]
![image](https://user-images.githubusercontent.com/6542180/90311602-2e367800-df2f-11ea-8c51-bb5fe8daad21.png)
ycm代码补全可以使用吗？安装vimplus时编译ycm的时候有没有报错呢？
