### ISSUE TITLE
g:NERDTreeIndicatorMapCustom' is deprecated

### ISSUE THREAD

**Issue by artemiseven** [chxuan/vimplus#292]
在ubuntu18.04安装完后用vim打开文件 , 会提示:
[nerdtree-git-status] option 'g:NERDTreeIndicatorMapCustom' is deprecated, please use 'g:NERDTreeGitStatusIndicatorMapCustom'
Press ENTER or type command to continue
后面修改.vimrc
--- a/.vimrc
+++ b/.vimrc
@@ -312,7 +312,7 @@ map <leader>w <Plug>(easymotion-bd-w)
 nmap <leader>w <Plug>(easymotion-overwin-w)

 " nerdtree-git-plugin
-let g:NERDTreeIndicatorMapCustom = {
+let g:NERDTreeGitStatusIndicatorMapCustom = {
貌似可以解决.

**Comment by fsqx** [comment]
多谢，刚装了一下也遇到同样的问题了，按您的方法已经改好了
