### ISSUE TITLE
;在normal模式下不起作用

### ISSUE THREAD

**Issue by LyndonKong** [chxuan/vimplus#295]
我使用的是VIM 8.2 huge，在加载vimplus以后`;`没办法使用。
**我想知道`;`被映射到什么按键上了**
我加载的插件除了vimplus的默认插件以外只有markdown preview, .vimrc文件只将leader键映射修改到了space上。

**Comment by chxuan** [comment]
@LyndonKong 你可以使用vim -u NONE -N命令来试试，该命令时启动vim不加载任何配置信息。

**Comment by LyndonKong** [comment]
> @LyndonKong 你可以使用vim -u NONE -N命令来试试，该命令时启动vim不加载任何配置信息。

您好，感谢回复。在不加载配置选项的情况下`;`可以正常使用。

**Comment by applejwjcat** [comment]
> > @LyndonKong 你可以使用vim -u NONE -N命令来试试，该命令时启动vim不加载任何配置信息。
> 
> 您好，感谢回复。在不加载配置选项的情况下`;`可以正常使用。

你可以使用命令行模式下
```
:verbose map ;
```
来查看是不是映射了什么键位？

**Comment by LyndonKong** [comment]
> > > @LyndonKong 你可以使用vim -u NONE -N命令来试试，该命令时启动vim不加载任何配置信息。
> > 
> > 
> > 您好，感谢回复。在不加载配置选项的情况下`;`可以正常使用。
> 
> 你可以使用命令行模式下
> 
> ```
> :verbose map ;
> ```
> 
> 来查看是不是映射了什么键位？

verbose map ;显示没有被映射，很奇怪为什么不能在使用f{char}以后使用;跳转到下一个目标

**Comment by applejwjcat** [comment]
我知道了，你一定是装了Leaderf 或者sneak之类的vim插件，所以你的f键被映射了，不再是vim自带的f，所以不能使用vim原生的；功能，你可以用上面的方法查看f键的映射，将它改为其他快捷键，就可以将原生的vim  ```f```查找键解放出来。
另外，我建议，vim新手学习vim脚本的时候最好用原生vim，带插件的有些配置你可能弄不太清楚

**Comment by LyndonKong** [comment]
> 我知道了，你一定是装了Leaderf 或者sneak之类的vim插件，所以你的f键被映射了，不再是vim自带的f，所以不能使用vim原生的；功能，你可以用上面的方法查看f键的映射，将它改为其他快捷键，就可以将原生的vim `f`查找键解放出来。
> 另外，我建议，vim新手学习vim脚本的时候最好用原生vim，带插件的有些配置你可能弄不太清楚

感谢您的帮助

**Comment by applejwjcat** [comment]
您好，如果问题解决的话，请把这个issue关了吧
