### ISSUE TITLE
虚拟机Ubuntu16.04 报错

### ISSUE THREAD

**Issue by gitccl** [chxuan/vimplus#296]
mkdir: 无法创建目录"/home/ccl/.vim": 文件已存在
ln: 无法创建符号链接'/home/ccl/.vim/colors': 权限不够
ln: 无法创建符号链接'/home/ccl/.vim/ftplugin': 权限不够
ln: 无法创建符号链接'/home/ccl/.vim/autoload': 权限不够
/home/ccl/.local/share/fonts: caching, new cache contents: 1 fonts, 0 dirs
/var/cache/fontconfig: not cleaning unwritable cache directory
/home/ccl/.cache/fontconfig: cleaning cache directory
/home/ccl/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
fatal: 不能为 '/home/ccl/.vim/plugged/YouCompleteMe' 创建先导目录: 权限不够
./install.sh: 第 423 行: cd: /home/ccl/.vim/plugged/YouCompleteMe: 没有那个文件或目录
Please choose to compile ycm with python2 or python3, if there is a problem with the current selection, please choose another one. [2/3] 3
Compile ycm with python3.
python3: can't open file './install.py': [Errno 2] No such file or directory
处理 /home/ccl/.vimrc 时发生错误:
第  124 行:
E117: 未定义的函数: plug#begin
第  126 行:
E492: 不是编辑器的命令: Plug 'chxuan/cpp-mode'
第  127 行:
E492: 不是编辑器的命令: Plug 'chxuan/vim-edit'
第  128 行:
E492: 不是编辑器的命令: Plug 'chxuan/change-colorscheme'
第  129 行:
E492: 不是编辑器的命令: Plug 'chxuan/prepare-code'
第  130 行:
E492: 不是编辑器的命令: Plug 'chxuan/vim-buffer'
第  131 行:
E492: 不是编辑器的命令: Plug 'chxuan/vimplus-startify'
第  132 行:
E492: 不是编辑器的命令: Plug 'chxuan/tagbar'
第  133 行:
E492: 不是编辑器的命令: Plug 'Valloric/YouCompleteMe'
第  134 行:
E492: 不是编辑器的命令: Plug 'Yggdroot/LeaderF'
第  135 行:
E492: 不是编辑器的命令: Plug 'mileszs/ack.vim'
第  136 行:
E492: 不是编辑器的命令: Plug 'easymotion/vim-easymotion'
第  137 行:
E492: 不是编辑器的命令: Plug 'haya14busa/incsearch.vim'
第  138 行:
E492: 不是编辑器的命令: Plug 'jiangmiao/auto-pairs'
第  139 行:
E492: 不是编辑器的命令: Plug 'scrooloose/nerdtree'
第  140 行:
E492: 不是编辑器的命令: Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
第  141 行:
E492: 不是编辑器的命令: Plug 'Xuyuanp/nerdtree-git-plugin'
第  142 行:
E492: 不是编辑器的命令: Plug 'godlygeek/tabular'
第  143 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-fugitive'
第  144 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-surround'
第  145 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-commentary'
第  146 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-repeat'
第  147 行:
E492: 不是编辑器的命令: Plug 'tpope/vim-endwise'
第  148 行:
E492: 不是编辑器的命令: Plug 'octol/vim-cpp-enhanced-highlight'
第  149 行:
E492: 不是编辑器的命令: Plug 'vim-airline/vim-airline'
第  150 行:
E492: 不是编辑器的命令: Plug 'vim-airline/vim-airline-themes'
第  151 行:
E492: 不是编辑器的命令: Plug 'ryanoasis/vim-devicons'
第  152 行:
E492: 不是编辑器的命令: Plug 'junegunn/vim-slash'
第  153 行:
E492: 不是编辑器的命令: Plug 'junegunn/gv.vim'
第  154 行:
E492: 不是编辑器的命令: Plug 'kana/vim-textobj-user'
第  155 行:
E492: 不是编辑器的命令: Plug 'kana/vim-textobj-indent'
第  156 行:
E492: 不是编辑器的命令: Plug 'kana/vim-textobj-syntax'
第  157 行:
E492: 不是编辑器的命令: Plug 'kana/vim-textobj-function'
第  158 行:
E492: 不是编辑器的命令: Plug 'sgur/vim-textobj-parameter'
第  159 行:
E492: 不是编辑器的命令: Plug 'Shougo/echodoc.vim'
第  160 行:
E492: 不是编辑器的命令: Plug 'terryma/vim-smooth-scroll'
第  161 行:
E492: 不是编辑器的命令: Plug 'rhysd/clever-f.vim'
第  162 行:
E492: 不是编辑器的命令: Plug 'vim-scripts/indentpython.vim'
第  169 行:
E117: 未定义的函数: plug#end
第  211 行:
E185: Cannot find color scheme 'onedark'
请按 ENTER 或其它命令继续

**Comment by gitccl** [comment]
我安装了两次都是这样的结果

**Comment by chxuan** [comment]
@gitccl 你好，你是按照教程来安装vimplus的吗？我看上面报的是权限不足，执行vimplus的安装脚本时加sudo没有？

**Comment by gitccl** [comment]
> @gitccl 你好，你是按照教程来安装vimplus的吗？我看上面报的是权限不足，执行vimplus的安装脚本时加sudo没有？

我直接执行的 `./install.sh` ， 没加sudo, 教程里不是说不用加sudo吗

**Comment by uinchir** [comment]
我装了很多次了，每一次都是按照教程傻瓜式安装的，好像就三步。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "guapi"<notifications@github.com&gt;; 
发送时间: 2020年8月28日(星期五) 晚上9:23
收件人: "chxuan/vimplus"<vimplus@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [chxuan/vimplus] 虚拟机Ubuntu16.04 报错 (#296)





  
@gitccl 你好，你是按照教程来安装vimplus的吗？我看上面报的是权限不足，执行vimplus的安装脚本时加sudo没有？
  
我直接执行的 ./install.sh ， 没加sudo, 教程里不是说不用加sudo吗
 
&mdash;

**Comment by gitccl** [comment]
> 我装了很多次了，每一次都是按照教程傻瓜式安装的，好像就三步。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "guapi"<notifications@github.com&gt;; 发送时间: 2020年8月28日(星期五) 晚上9:23 收件人: "chxuan/vimplus"<vimplus@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [chxuan/vimplus] 虚拟机Ubuntu16.04 报错 (#296) @gitccl 你好，你是按照教程来安装vimplus的吗？我看上面报的是权限不足，执行vimplus的安装脚本时加sudo没有？ 我直接执行的 ./install.sh ， 没加sudo, 教程里不是说不用加sudo吗 &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是按照那三步来装的，装到最后一步就出现了我发的那个错误

**Comment by gitccl** [comment]
加了个sudo解决了
