### ISSUE TITLE
vimplus跟neovim兼容吗

### ISSUE THREAD

**Issue by MiraculousMoon** [chxuan/vimplus#301]
我按照neovim的迁移方法试了一下，目前没啥问题

**Comment by chxuan** [comment]
@MiraculousMoon 你好，目前vimplus的脚本不支持neovim，但是vimplus里面的插件应该是支持的

**Comment by MiraculousMoon** [comment]
> @MiraculousMoon 你好，目前vimplus的脚本不支持neovim，但是vimplus里面的插件应该是支持的

好的 谢谢回复
