### ISSUE TITLE
关键字查找方法

### ISSUE THREAD

**Issue by yexuesong** [chxuan/vimplus#32]
我现在通过`/`无法查找关键字

**Comment by chxuan** [comment]
@yexuesong 可以的呢

**Comment by yexuesong** [comment]
只是需要`:/`而不是`/` ，另外，请问下在我在复制一段代码并粘贴到装了插件的vim中，会出现缩进异常。单独的vim是不会的。
目前我只装了一下插件
```
Plugin 'VundleVim/Vundle.vim'                                
Plugin 'scrooloose/nerdtree'                                 
Plugin 'Valloric/YouCompleteMe'                              
Plugin 'tpope/vim-fugitive'                                  
Plugin 'vim-airline/vim-airline'
```
会出现这种情况：
![image](https://user-images.githubusercontent.com/25861775/38719258-82d534ae-3f23-11e8-8ec3-730e04b91211.png)

请问您知道是怎么回事吗？

**Comment by yexuesong** [comment]
@chxuan

**Comment by chxuan** [comment]
@yexuesong 
<img width="890" alt="qq20180413-200120 2x" src="https://user-images.githubusercontent.com/6542180/38733759-c049a388-3f55-11e8-9e0c-ce57404c2c0c.png">我的可以呢

**Comment by chxuan** [comment]
@yexuesong 如果粘贴的代码出现了不对齐，你可以使用gg=G命令来进行代码对其，我的好像没有出现这种情况呢
