### ISSUE TITLE
没有管理员权限，如何安装vimplus

### ISSUE THREAD

**Issue by hxf0223** [chxuan/vimplus#325]
在服务器上开发，没有管理员权限，并且不能随便在系统目录下安装软件。请问可以较方便的实现：修改脚本即可在用户权限安装吗？

**Comment by chxuan** [comment]
@hxf0223 你好，如果没有管理员权限是不能安装vimplus的哦，因为vimplus依赖的一些软件需要管理员权限才能安装

**Comment by hxf0223** [comment]
@chxuan 谢谢你的答复！vimplus提供的完整套件，安装跟使用都很方便；希望vimplus持续演进，越来越强大。有可能的话，我看能否贡献一份力量。
