### ISSUE TITLE
WSL Debian 10 ,vim 8.2.423,但是使用vimplus安装仍然会在根目录创建vim82文件夹，这个可以删除吗

### ISSUE THREAD

**Issue by NBSOD** [chxuan/vimplus#330]

**Comment by uinchir** [comment]
我在安装这个软件的时候，带入了病毒，不知道会不会是代码里带的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Nowhere"<notifications@github.com&gt;; 
发送时间: 2021年1月15日(星期五) 下午2:29
收件人: "chxuan/vimplus"<vimplus@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [chxuan/vimplus] WSL Debian 10 ,vim 8.2.423,但是使用vimplus安装仍然会在根目录创建vim82文件夹，这个可以删除吗 (#330)

**Comment by NBSOD** [comment]
> 我在安装这个软件的时候，带入了病毒，不知道会不会是代码里带的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Nowhere"<notifications@github.com&gt;; 发送时间: 2021年1月15日(星期五) 下午2:29 收件人: "chxuan/vimplus"<vimplus@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [chxuan/vimplus] WSL Debian 10 ,vim 8.2.423,但是使用vimplus安装仍然会在根目录创建vim82文件夹，这个可以删除吗 (#330) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by NBSOD** [comment]
@uinchir 应该不会吧。。。一直在用这个增强vim，你也是用的WSL？会不会是windows杀毒软件误报了呢
