### ISSUE TITLE
在更新时发现YCM连接错误

### ISSUE THREAD

**Issue by jimmyyukio** [chxuan/vimplus#334]
在.vimrc中YCM仓库名是Valloric/YouCompleteMe，但我发现现在在github是它的仓库名变成了ycm-core/YouCompleteMe
![image](https://user-images.githubusercontent.com/60495173/107051710-becb8200-6807-11eb-8553-849f368b311a.png)

**Comment by Ro0tk1t** [comment]
你可以先删掉原来的ycm，手动安装最新的ycm
```bash
cd ~/.vim/plugged
rm -rf YouCompleteMe
git clone https://github.com/ycm-core/YouCompleteMe.git
cd YouCompleteMe
./install.py
```

**Comment by jimmyyukio** [comment]
谢谢！已经解决了
