### ISSUE TITLE
新手不会使用

### ISSUE THREAD

**Issue by pengzhangzhi** [chxuan/vimplus#343]
我刚刚接触linux，想在linux环境下编程，于是了解到了Vimplus，安装完后，并不知道应该如何开始？请问有没有适合新手的教程？quick start之类的文档。我目前只知道如何打开vim...

**Comment by HarsonLau** [comment]
在命令行运行vimtutor,这是vim自带的教程，可以带你过一遍vim的基本操作，但也仅限于基本操作了
