### ISSUE TITLE
xshell下vim-devicons不能正确显示图标

### ISSUE THREAD

**Issue by HGtz2222** [chxuan/vimplus#35]
FAQ中关于xshell下使用vim-devicons不能显示图标问题是安装 DejaVuSansMono. 请问下这个字体是在windows下安装还是在Linux下安装, 需要修改其他额外的配置么? 

目前在windows下和linux下安装都不生效. 球大佬解惑~~

环境:
Windows: Xshell5
Linux: Centos7 x86_64

**Comment by HGtz2222** [comment]
xshell是否是对字体有一定的限制？试了几个字体， 发现安装之后， xshell不能把字体设置成新安装的字体

**Comment by HGtz2222** [comment]
目前字体已经安装成功, 但是图标仍然不能正确显示. 
![](https://i.imgur.com/ofNtz2B.png)

**Comment by HGtz2222** [comment]
问题解决了. 
vim-devicons需要Nerd Font. 但是xshell只支持等宽字体, 因此Nerd Font中相当一部分字体安装后, xshell不能正确识别(例如FAQ中提到的DejaVuSansMono, 并不能被xshell识别). 
目前粗略尝试了下, 以下几个Nerd Font字体是可以能够被xshell识别的.

https://github.com/artofrawr/powerline-fonts/tree/master/fonts/SFMono
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/DroidSansMono/complete/Droid%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/3270/Medium/complete/3270-Medium%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf
https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/AurulentSansMono/complete/AurulentSansMono-Regular%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.otf

没有尝试更多的字体. 理论上来讲, 需要这个字体首先是 Nerd Font, 其次需要是等宽字体. 这样就能够在xshell正确显示图标.

**Comment by chxuan** [comment]
@HGtz2222 恩恩,但是我安装DejaVuSansMono就可以呢
