### ISSUE TITLE
ubuntu20安装完后用vim打开文件后提示这个错误，也没提示、报错功能，为啥呢？之前安装的时候都好好的/(ㄒoㄒ)/~~

### ISSUE THREAD

**Issue by Joeneversharefood** [chxuan/vimplus#362]
The ycmd server SHUT DOWN (restart with ':YcmRestartServer'). YCM core l...ompil
e YCM before using it. Follow the instructions in the documentation.

**Comment by liyongzheng666** [comment]
请问您这个问题是如何解决的呢？
