### ISSUE TITLE
在Termux中无法使用ycmd

### ISSUE THREAD

**Issue by lingxh** [chxuan/vimplus#389]
报错提示
The ycmd server SHUT DOWN (restart with ':YcmRestartSe...Logs
ycmd_38952_stderr_63xabxqt.log' to check the logs.

**Comment by liuhq** [comment]
> 报错提示 The ycmd server SHUT DOWN (restart with ':YcmRestartSe...Logs ycmd_38952_stderr_63xabxqt.log' to check the logs.

https://github.com/chxuan/vimplus/issues/383#issuecomment-1030087329

python2重新编译~
