### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by colorsakura** [chxuan/vimplus#39]
![screenshot from 2018-05-13 09-37-26](https://user-images.githubusercontent.com/32534829/39962970-8f05de42-5691-11e8-9a52-ce38b5c5026d.png)
Droid Sans Mono Nerd Font yi shi yong

**Comment by colorsakura** [comment]
wo shi centos7

**Comment by chxuan** [comment]
@colorsakura 你需要设置nerd-front字体(Droid Sans Mono Nerd Font)，你可以看下我的readme，里面有介绍
