### ISSUE TITLE
为什么修改用户配置文件不起作用呢？

### ISSUE THREAD

**Issue by LIend0** [chxuan/vimplus#403]
我修改了.vimrc.custom.config 之后没有作用
哪怕我只是把注释的 setcursorcolumn 打开也依然不起作用

**Comment by bfmhno3** [comment]
不要更改 `.vimplus` 下的 `.vimrc.custom.config` 和 `.vimrc.custom.plugins`
因为 `~/.vimrc` 并不读取这两个文件，而是读取 `~` 下的相应文件
执行下列命令：
```bash
cd ~
ls -la | grep .vimrc.custom
```
即可找到需要更改的文件
