### ISSUE TITLE
tagbar有bug，打开大文件光标移动非常慢，像卡屏了。

### ISSUE THREAD

**Issue by if2012** [chxuan/vimplus#49]
进文件光标加载慢，而且移动到文件末尾的时候非常非常卡。移除这个插件一切正常

有人发现了同样的问题，建议替换为taglist或者其它的。
https://github.com/majutsushi/tagbar/issues/494

**Comment by chxuan** [comment]
@if2012 好的，谢谢反馈，感谢使用vimplus！

**Comment by if2012** [comment]
@chxuan 你那边有这种情况吗？稍微大一点的文件比如3000多行的只要开了这个插件进去之后就会这样

**Comment by chxuan** [comment]
@if2012 确实是tagbar和折叠影响到了vim的启动速度，谢谢反馈！

**Comment by if2012** [comment]
@chxuan tagbar只有看开发者去解决吗，我大概看了下可能是GetNearbyTag这个函数引起的。2.4以前的版本不会有大文件光标卡屏的问题。

**Comment by chxuan** [comment]
@if2012 目前vimplus的配置删除了代码折叠功能，打开大文件确实会影响到启动速度，但还是保留了tagbar，因为目前tagbar相对于taglist来说功能更完善，目前就只有期待tagbar的开发者去解决这个问题了，或者使用你说的2.4以前的版本。

**Comment by chxuan** [comment]
@if2012 我已经将majutsushi/tagbar的v2.3版本保存到了chxuan/tagbar，目前vimplus将会使用chxuan/tagbar 版本的tagbar，现在就不用担心vim打开大文件时，光标卡顿的情况了

**Comment by if2012** [comment]
@chxuan 找到bug了，tagbar和vim-airline冲突了
加入一句 let g:airline#extensions#tagbar#enabled = 0，就能用最新版本的tagbar了。
