### ISSUE TITLE
安装不成功

### ISSUE THREAD

**Issue by njudml** [chxuan/vimplus#57]
ubuntu16.04 64位
安装完vim 都被卸载了
vim版本7.4.1689

**Comment by njudml** [comment]
重新安装一次又成功了

**Comment by chxuan** [comment]
@njudml ubuntu16.04下的vim的版本比较低，不满足ycm的需求，所以vimplus会自动卸载低版本的vim，然后编译安装最新的vim，遇到什么问题都可以问我，欢迎使用vimplus！
