### ISSUE TITLE
Not an editor command:Plug 'xxxxxx'

### ISSUE THREAD

**Issue by shayneeee** [chxuan/vimplus#59]
vimplus和所有插件都显示安装成功。但是运行的时候显示如题目的报错，好像是Plug不能识别，我重新单独装了一下Plug也没有用，请问怎么办呢，系统是centos7.4
![tim 20180722004639](https://user-images.githubusercontent.com/32152117/43038259-c07fc1ca-8d48-11e8-800f-96e5a2536a09.png)
![tim 20180722004652](https://user-images.githubusercontent.com/32152117/43038261-c5eb6a56-8d48-11e8-9e23-3fb6a54c6bd3.png)

**Comment by if2012** [comment]
你是在root用户下装的吗

**Comment by if2012** [comment]
默认是装在home目录下的，你看下.vim目录在哪

**Comment by shayneeee** [comment]
我是在一个自定义用户usrname里面安装的，安装完发现.vim  和.vimrc 都在root目录下，我把这些拷贝回/home/usrname/里面，用usrname登陆可以使用vim 但是root用户登陆还是那种报错 @if2012

**Comment by shayneeee** [comment]
我后来在root用户登陆里也运行了vimplus的安装脚本，想在root和usrname里面都可以使用，现在root用户还是不能用 @if2012

**Comment by if2012** [comment]
@shayneeee 两步就行，不用改其它东西
ln /home/usrname/.vimrc /root/.vimrc
ln /home/usrname/.vim /root/

**Comment by if2012** [comment]
你先在usrname用户下装，不要root登录，然后按照上面步骤创建一下软链接

**Comment by if2012** [comment]
或者你usrname用户已经能用了，就直接root登录，删掉之前的，再建一下软链接

**Comment by shayneeee** [comment]
用了上面的软连接root还是不能用。。很绝望 @if2012

**Comment by if2012** [comment]
你在root目录下ls -a截图给我看看

**Comment by shayneeee** [comment]
![tim](https://user-images.githubusercontent.com/32152117/43043022-6b838c46-8dbc-11e8-9662-cda2de9b5257.png)
@if2012 这样子的，连接感觉对着呢

**Comment by if2012** [comment]
为什么.vim下面还有.vim，你先把这些乱七八糟的全删了，包括root下的.vim .vimplus .vimrc

**Comment by if2012** [comment]
然后按照我上面哪两个步骤来，只要替换username为你的用户名，其它不要改，不成功你来打我

**Comment by shayneeee** [comment]
我把那些都删了，然后把root里面的.vim .vimrc都连接到用户里面对应的文件，还是只能在用户使用。root用不了。 @if2012

**Comment by if2012** [comment]
错误信息截图

**Comment by shayneeee** [comment]
错误还是和之前的一样, 一大堆Not an editor command :Plug 'xxxxxxx'

**Comment by if2012** [comment]
root用户下vim .vimrc看下是跟对应用户一样吗？你自己确认下，如果.vim和.vimrc都是一样不存在root用不了的

**Comment by if2012** [comment]
我怀疑你root下.vim目录下autoload里面根本没有plug.vim这个文件

**Comment by shayneeee** [comment]
![tim 20180722155133](https://user-images.githubusercontent.com/32152117/43043476-2227eea6-8dc7-11e8-8376-11f3b9eaf137.png)
我也是这么觉得应该可以用。。但是就是报错的

**Comment by shayneeee** [comment]
有plug.vim的

**Comment by shayneeee** [comment]
目前在/root/里面建两个 软 链接，或者直接把/home/shayne/.vim复制过来都是报同样的错

**Comment by shayneeee** [comment]
实在不行我就只在用户里面使用吧。十分感谢 @if2012 @chxuan 对我的帮助
目前发现的一些疑问：我在shayne 登陆使用sudo ./install.sh安装完成以后  .vim/  .vimrc自动出现在/root/目录中。/home/shayne/里面没有
其次我的centos7.4中只有两个用户root 和shayne同属root用户组，安装以后有些文件显示属于shayne用户组

**Comment by shayneeee** [comment]
发现用户组不正确的原因了
![tim 20180722161701](https://user-images.githubusercontent.com/32152117/43043651-c239275e-8dca-11e8-906b-ba801a5134a1.png)

**Comment by if2012** [comment]
注释后再分别装一下，不要用链接了。因为你两个都是root用户组

**Comment by shayneeee** [comment]
破案了！！！
因为一般用户都可以用但是root却不能用。所以我怀疑是vim的问题，我以为是不是调用了不同的vim
于是find了一下
![find](https://user-images.githubusercontent.com/32152117/43043888-6aa87644-8dce-11e8-9fc1-0f2671ec2e6d.png)
![path](https://user-images.githubusercontent.com/32152117/43043900-b8bbffea-8dce-11e8-9617-dcb7c49afa6a.png)

发现root用户组下使用绝对路径+vim都可以使用！！
所以问题显而易见了。。
alias vi='vim'
因为我记得centos已经自动这样默认设置过了，而且我新建的用户都有这样的默认设置，搞不懂为啥子我的root没有。。
 @if2012 @chxuan 再次感谢！！！！

**Comment by chxuan** [comment]
@shayneeee @if2012 目前我已经修复了vimplus在centos上的安装bug，在普通用户下安装不会安装到root用户下了，并且vimplus会自动下载最新的vim进行编译安装，替换掉centos上低版本的vim，欢迎使用vimplus！
