### ISSUE TITLE
ycm遇到模板好像会产生误报?

### ISSUE THREAD

**Issue by kangseung** [chxuan/vimplus#62]
boost::property_tree::ptree parser;
        boost::property_tree::json_parser::read_json("/setting.json",parser);
        return parser.get<std::string>(name);

第三行的get<std::string>这样写就会报错,但是可以编译通过.
member reference base type "boost::property_tree::ptree" (aka 'int')is not a structure or union

**Comment by chxuan** [comment]
@kangseung 这个可能是ycm的问题，你需要去ycm官网提issues

**Comment by kangseung** [comment]
好的
