### ISSUE TITLE
centos 7 版本貌似没有用vim7.4+以上的版本

### ISSUE THREAD

**Issue by amoyiki** [chxuan/vimplus#63]
https://github.com/chxuan/vimplus/blob/3f6be8fbef78a67611bd4fd615b9a9bc4f0dd66d/install.sh#L69

这里直接安装的vim版有点低

**Comment by chxuan** [comment]
截个图给我看下，你的centos7下的vim版本，之前我在centos7下也正常使用过vimplus

**Comment by amoyiki** [comment]
之前是VIM 7.4，然后我自己编译安装了最新的vim，外加注释了yum install vim 这行才装上。
centos 7 腾讯云这边默认下载的vim版本应该都是vim 7.4

**Comment by chxuan** [comment]
@amoyiki 目前我已经修复了vimplus在centos上的安装bug了，执行vimplus的安装脚本时会自动下载vim源码进行编译安装vim
