### ISSUE TITLE
在Ubuntu18.04环境下安装之后，提示找不到.viminfo

### ISSUE THREAD

**Issue by iceberg2271** [chxuan/vimplus#68]
安装过程没有出现什么问题，但是安装结束提示找不到viminfo

**Comment by chxuan** [comment]
截个图看看，viminfo是vim自己生成用于保存一些状态信息的，你再次打开vim应该就有了

**Comment by iceberg2271** [comment]
![image](https://user-images.githubusercontent.com/20139509/44182214-92ec4b80-a138-11e8-8b20-01b4b2823ab1.png)
看上去是这个样子的

**Comment by chxuan** [comment]
@iceberg2271 你先打开一个文件比如说vim main.cpp，然后再执行vim启动页，你试试看。

**Comment by iceberg2271** [comment]
可以直接打开，这说明没问题吗？

**Comment by iceberg2271** [comment]
打开cpp没有问题，但是直接vim还是有这个问题

**Comment by chxuan** [comment]
你看下你的~目录下有没有.viminfo文件并确保其文件可读权限
