### ISSUE TITLE
terminator终端复制问题

### ISSUE THREAD

**Issue by ricardoZhao** [chxuan/vimplus#69]
问题描述:
   系统ubuntu16.04 
   终端使用的是　terminator
   字体设置为Droid Sans Mono Nerd Font Complete.otf后，
　复制粘贴的时候会有问题，比如我复制了https://github.com/chxuan/vimplus/issues/new
　粘贴到终端上就为：　 0~https://github.com/chxuan/vimplus/issues/new1~
　用其它的终端和其它的字体没有问题

**Comment by chxuan** [comment]
可能是你使用的那个终端不支持nerd font

**Comment by chxuan** [comment]
@ricardoZhao 也可能是该字体不兼容terminator，你看下这个链接：https://github.com/ryanoasis/nerd-fonts/issues/238，你下一个最新的字体试试
