### ISSUE TITLE
shellcraft不支持

### ISSUE THREAD

**Issue by a252937166** [chxuan/vimplus#77]
mac上的shellcraft使用vimplus之后，一片绿色。。。

**Comment by chxuan** [comment]
你的vimplus安装在其他电脑上，然后你在mac上用shellcraft去连接那台电脑使用vimplus时一片绿色吗？可以截个图吗？

**Comment by a252937166** [comment]
![image](https://user-images.githubusercontent.com/16303294/45561985-a4ca2700-b87b-11e8-80b2-0068aad007dc.png)
windows上用xshell没问题

**Comment by chxuan** [comment]
@a252937166 vim -u NONE -N，开启vim时不加载vimrc文件，你尝试用这种方式启动vim试试

**Comment by a252937166** [comment]
@chxuan这样就没问题，但是就和vi一样了

**Comment by chxuan** [comment]
@a252937166 因为我在mac上没有用shellcraft这个软件，所以具体也不知道是什么问题，你可以试试其他的ssh client，我在mac上直接用的iteam2结合ssh命令来远程使用vimplus，没有出现这个问题。

**Comment by a252937166** [comment]
自带的终端没有问题
