### ISSUE TITLE
vim状态栏乱码和NERD_tree缩进不正常的问题

### ISSUE THREAD

**Issue by chenchuangchn** [chxuan/vimplus#8]
您好，安装好vimplus后发现NERD_tree同一目录下的文件夹和文件缩进不一样，并且文件名前面是乱码(没有中文)。状态栏上也有乱码。
guifont的设置为 Droid Sans Mono for Powerlin Nerd Font Complete 12。但是没解决。
求指导

**Comment by chxuan** [comment]
请问你使用的什么系统，界面版，还是非界面版本，若是非界面版本可以将~/.vim/bundle/里面的vim-devicons插件删除

**Comment by chenchuangchn** [comment]
我用的是官方Ubuntu14.04的桌面版，是有界面的。请问如何解决。

**Comment by chxuan** [comment]
你也可以按照上面的方法试试

**Comment by chenchuangchn** [comment]
我按上面方法试了，确实左边的树形结构确实正常了。谢谢
